package io.github.qwqgong.androidcyaml

import android.os.Process
import android.util.Log
import java.io.BufferedInputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.net.InetAddress
import java.net.InetSocketAddress
import java.net.ServerSocket
import java.net.Socket
import java.net.URI
import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import java.util.Base64
import java.util.Locale
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.RejectedExecutionException
import java.util.concurrent.SynchronousQueue
import java.util.concurrent.ThreadFactory
import java.util.concurrent.ThreadPoolExecutor
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger

/*
 * Loopback-only HTTP CONNECT proxy used to preserve an XHTTP node's configured
 * server address while WebView owns TLS and HTTP. Chromium opens a tunnel for
 * the URL authority, then this proxy dials the exact mihomo server and port.
 * TLS remains end-to-end between WebView and the remote endpoint, so SNI, ALPN
 * and the ClientHello are still generated by System WebView. Unknown
 * authorities are rejected; this is not an open proxy.
 */
class WebViewConnectProxy(
    private val socketProtector: SocketProtector,
    private val routeProvider: NetworkRouteProvider,
) : AutoCloseable {
    private val listener = ServerSocket()
    private val workers = ThreadPoolExecutor(
        0,
        MAX_WORKER_THREADS,
        60L,
        TimeUnit.SECONDS,
        SynchronousQueue(),
        ProxyThreadFactory(),
    )
    private val bindingsByKey = ConcurrentHashMap<String, TargetBinding>()
    private val bindingsByUsername = ConcurrentHashMap<String, TargetBinding>()
    private val authorities: MutableSet<String> = ConcurrentHashMap.newKeySet()
    private val sockets: MutableSet<Socket> = ConcurrentHashMap.newKeySet()
    private val closed = AtomicBoolean(false)
    private val authenticationRealm = "AndroidCyaml-XHTTP-" + UUID.randomUUID()

    init {
        // ProxyConfig below uses this listener address verbatim. Do not use
        // getLoopbackAddress(): Android commonly returns ::1, while a
        // 127.0.0.1 proxy rule cannot reach an IPv6-only ServerSocket.
        listener.bind(InetSocketAddress(InetAddress.getByAddress(IPV4_LOOPBACK), 0), 64)
        workers.execute { acceptLoop() }
    }

    fun port(): Int = listener.localPort

    fun authority(): String = (listener.inetAddress.hostAddress ?: "") + ':' + port()

    fun register(urlValue: String, serverAddress: String?): TargetBinding {
        val url = try {
            URI.create(urlValue)
        } catch (exception: IllegalArgumentException) {
            throw IOException("无效的 WebView XHTTP URL", exception)
        }
        val host = url.host
        if (host.isNullOrBlank()) {
            throw IOException("WebView XHTTP URL 缺少主机名")
        }
        val port = if (url.port > 0) url.port else 443
        val target = parseAuthority(serverAddress, port)
        val authority = authorityKey(host, port)
        val bindingKey = authority + '\n' + authorityKey(target.host, target.port)
        val binding = bindingsByKey.computeIfAbsent(bindingKey) {
            TargetBinding(bindingKey, authority, target)
        }
        bindingsByUsername.putIfAbsent(binding.username(), binding)
        authorities.add(authority)
        return binding
    }

    fun isAuthenticationRealm(realm: String?): Boolean = authenticationRealm == realm

    // Drops a binding created by register(), e.g. once its origin page has
    // been idle-evicted. Without this, a long session that visits many XHTTP
    // origins grows bindingsByKey/bindingsByUsername/authorities for the
    // lifetime of the dialer.
    fun unregister(binding: TargetBinding) {
        bindingsByKey.remove(binding.key(), binding)
        bindingsByUsername.remove(binding.username(), binding)
        val stillReferenced = bindingsByKey.values.any { it.authority() == binding.authority() }
        if (!stillReferenced) {
            authorities.remove(binding.authority())
        }
    }

    private fun acceptLoop() {
        while (!closed.get()) {
            try {
                val client = listener.accept()
                client.tcpNoDelay = true
                sockets.add(client)
                try {
                    workers.execute { handle(client) }
                } catch (exception: RejectedExecutionException) {
                    // Worker pool is saturated; drop this one tunnel instead of
                    // letting the exception escape and kill the accept loop.
                    closeSocket(client)
                }
            } catch (ignored: IOException) {
                // Listener closure and transient accept failures both end this
                // iteration. The loop exits once close() flips the state.
            }
        }
    }

    private fun handle(client: Socket) {
        var upstream: Socket? = null
        try {
            val input = BufferedInputStream(client.getInputStream())
            val output = client.getOutputStream()
            val requestLine = readAsciiLine(input) ?: return
            val parts = requestLine.split(" ", limit = 3)
            if (parts.size != 3 || !"CONNECT".equals(parts[0], ignoreCase = true)) {
                writeFailure(output, 405, "Method Not Allowed")
                return
            }
            val authority = parts[1]
            var proxyAuthorization: String? = null
            while (true) {
                val line = readAsciiLine(input)
                if (line == null || line.isEmpty()) {
                    break
                }
                val separator = line.indexOf(':')
                if (separator > 0 &&
                    "Proxy-Authorization".equals(line.substring(0, separator), ignoreCase = true)
                ) {
                    proxyAuthorization = line.substring(separator + 1).trim()
                }
            }

            val requested = parseAuthority(authority, 443)
            val requestedAuthority = authorityKey(requested.host, requested.port)
            if (!authorities.contains(requestedAuthority)) {
                writeFailure(output, 403, "Forbidden")
                return
            }
            val binding = authenticatedBinding(requestedAuthority, proxyAuthorization)
            if (binding == null) {
                writeAuthenticationRequired(output)
                return
            }

            try {
                upstream = connectUpstream(binding.target())
                if (binding.connectionLogged.compareAndSet(false, true)) {
                    try {
                        Log.i(TAG, "Exact CONNECT target active: " + binding.targetDescription())
                    } catch (ignored: RuntimeException) {
                        // Local JVM tests do not provide android.util.Log.
                    }
                }
            } catch (exception: SocketProtectionException) {
                writeFailure(output, 502, "VPN Protect Failed")
                return
            }
            output.write(
                "HTTP/1.1 200 Connection Established\r\n\r\n".toByteArray(
                    StandardCharsets.US_ASCII,
                ),
            )
            output.flush()

            val upstreamSocket = upstream
            try {
                workers.execute {
                    copyAndClose(
                        upstreamSocket,
                        client,
                        inputOf(upstreamSocket),
                        outputOf(client),
                    )
                }
            } catch (exception: RejectedExecutionException) {
                // Worker pool is saturated; the finally block below still
                // closes both sockets, ending this tunnel cleanly.
                return
            }
            copy(input, upstream.getOutputStream())
        } catch (ignored: IOException) {
            // CONNECT tunnels routinely end with one side closing first.
        } finally {
            closeSocket(client)
            closeSocket(upstream)
        }
    }

    private fun connectUpstream(destination: HostPort): Socket {
        val route = routeProvider.current() ?: throw IOException("WebView XHTTP 底层网络不可用")

        var lastFailure: IOException? = null
        val addresses = route.resolve(destination.host)
        if (addresses == null || addresses.isEmpty()) {
            throw IOException("WebView XHTTP 无法解析目标服务器")
        }
        for (address in addresses) {
            val candidate = Socket()
            sockets.add(candidate)
            try {
                // Force creation of the socket FD, bind it to the selected
                // non-VPN network, then exempt that exact FD before connect().
                candidate.tcpNoDelay = true
                route.bind(candidate)
                if (!protect(candidate)) {
                    throw SocketProtectionException()
                }
                candidate.connect(
                    InetSocketAddress(address, destination.port),
                    CONNECT_TIMEOUT_MILLIS,
                )
                return candidate
            } catch (exception: SocketProtectionException) {
                closeSocket(candidate)
                throw exception
            } catch (exception: IOException) {
                lastFailure = exception
                closeSocket(candidate)
            }
        }
        throw lastFailure ?: IOException("WebView XHTTP 无法连接目标服务器")
    }

    private fun copyAndClose(
        sourceSocket: Socket,
        destinationSocket: Socket,
        input: InputStream?,
        output: OutputStream?,
    ) {
        try {
            if (input != null && output != null) {
                copy(input, output)
            }
        } catch (ignored: IOException) {
            // CONNECT tunnels routinely end with one side closing first.
        } finally {
            closeSocket(sourceSocket)
            closeSocket(destinationSocket)
        }
    }

    private fun writeAuthenticationRequired(output: OutputStream) {
        output.write(
            (
                "HTTP/1.1 407 Proxy Authentication Required\r\n" +
                    "Proxy-Authenticate: Basic realm=\"" + authenticationRealm + "\"\r\n" +
                    "Proxy-Connection: close\r\n" +
                    "Connection: close\r\n" +
                    "Content-Length: 0\r\n\r\n"
                ).toByteArray(StandardCharsets.US_ASCII),
        )
        output.flush()
    }

    private fun authenticatedBinding(
        requestedAuthority: String,
        authorization: String?,
    ): TargetBinding? {
        if (authorization == null || !authorization.regionMatches(0, "Basic ", 0, 6, true)) {
            return null
        }
        val credentials = try {
            String(
                Base64.getDecoder().decode(authorization.substring(6).trim()),
                StandardCharsets.UTF_8,
            )
        } catch (exception: IllegalArgumentException) {
            return null
        }
        val separator = credentials.indexOf(':')
        if (separator <= 0) {
            return null
        }
        val binding = bindingsByUsername[credentials.substring(0, separator)]
        if (binding == null || binding.authority() != requestedAuthority) {
            return null
        }
        val supplied = credentials.substring(separator + 1).toByteArray(StandardCharsets.UTF_8)
        val expected = binding.password().toByteArray(StandardCharsets.UTF_8)
        return if (MessageDigest.isEqual(supplied, expected)) binding else null
    }

    private fun protect(socket: Socket): Boolean = try {
        socketProtector.protect(socket)
    } catch (ignored: RuntimeException) {
        false
    }

    private fun closeSocket(socket: Socket?) {
        if (socket == null) {
            return
        }
        sockets.remove(socket)
        try {
            socket.close()
        } catch (ignored: IOException) {
            // Tunnel teardown is best effort.
        }
    }

    override fun close() {
        if (!closed.compareAndSet(false, true)) {
            return
        }
        try {
            listener.close()
        } catch (ignored: IOException) {
            // Listener teardown is best effort.
        }
        for (socket in sockets.toTypedArray()) {
            closeSocket(socket)
        }
        workers.shutdownNow()
        bindingsByKey.clear()
        bindingsByUsername.clear()
        authorities.clear()
    }

    data class HostPort(val host: String, val port: Int)

    class TargetBinding(
        private val key: String,
        private val authority: String,
        private val target: HostPort,
    ) {
        private val profileName = "androidcyaml-xhttp-" + UUID.nameUUIDFromBytes(
            key.toByteArray(StandardCharsets.UTF_8),
        )
        private val username = UUID.randomUUID().toString()
        private val password = UUID.randomUUID().toString()

        internal val connectionLogged = AtomicBoolean(false)

        fun key(): String = key

        fun authority(): String = authority

        fun target(): HostPort = target

        fun targetDescription(): String {
            val host = target.host
            return (if (host.indexOf(':') >= 0) "[$host]" else host) + ':' + target.port
        }

        fun profileName(): String = profileName

        fun username(): String = username

        fun password(): String = password

        fun authorizationHeader(): String = "Basic " + Base64.getEncoder().encodeToString(
            "$username:$password".toByteArray(StandardCharsets.UTF_8),
        )
    }

    fun interface SocketProtector {
        fun protect(socket: Socket): Boolean
    }

    fun interface NetworkRouteProvider {
        fun current(): NetworkRoute?
    }

    interface NetworkRoute {
        fun resolve(host: String): Array<InetAddress>?

        fun bind(socket: Socket)
    }

    private class SocketProtectionException : IOException()

    private class ProxyThreadFactory : ThreadFactory {
        private val nextId = AtomicInteger()

        override fun newThread(runnable: Runnable): Thread {
            val thread = Thread(
                {
                    try {
                        Process.setThreadPriority(Process.THREAD_PRIORITY_DISPLAY)
                    } catch (ignored: RuntimeException) {
                        // Local JVM tests do not provide android.os.Process.
                    }
                    runnable.run()
                },
                "AndroidCyaml-WebViewProxy-" + nextId.incrementAndGet(),
            )
            thread.isDaemon = true
            return thread
        }
    }

    private companion object {
        const val TAG = "AndroidCyaml/WebViewProxy"
        const val MAX_LINE_BYTES = 16 * 1024
        const val CONNECT_TIMEOUT_MILLIS = 30_000

        val IPV4_LOOPBACK = byteArrayOf(127, 0, 0, 1)

        // Two worker threads per active CONNECT tunnel (accept handler + the
        // reverse-direction copy), plus the permanent accept-loop thread. This
        // caps runaway thread growth while still scaling like a cached pool.
        const val MAX_WORKER_THREADS = 256

        fun copy(input: InputStream, output: OutputStream) {
            val buffer = ByteArray(32 * 1024)
            while (true) {
                val count = input.read(buffer)
                if (count < 0) {
                    return
                }
                if (count > 0) {
                    output.write(buffer, 0, count)
                    output.flush()
                }
            }
        }

        fun readAsciiLine(input: InputStream): String? {
            val buffer = ByteArray(MAX_LINE_BYTES)
            var length = 0
            while (length < buffer.size) {
                val value = input.read()
                if (value < 0) {
                    return if (length == 0) {
                        null
                    } else {
                        String(buffer, 0, length, StandardCharsets.US_ASCII)
                    }
                }
                if (value == '\n'.code) {
                    if (length > 0 && buffer[length - 1] == '\r'.code.toByte()) {
                        length--
                    }
                    return String(buffer, 0, length, StandardCharsets.US_ASCII)
                }
                buffer[length++] = value.toByte()
            }
            throw IOException("CONNECT 请求头行过长")
        }

        fun writeFailure(output: OutputStream, status: Int, reason: String) {
            output.write(
                (
                    "HTTP/1.1 " + status + " " + reason +
                        "\r\nConnection: close\r\nContent-Length: 0\r\n\r\n"
                    ).toByteArray(StandardCharsets.US_ASCII),
            )
            output.flush()
        }

        fun parseAuthority(value: String?, fallbackPort: Int): HostPort {
            if (value.isNullOrBlank()) {
                throw IOException("WebView XHTTP 缺少目标服务器地址")
            }
            val text = value.trim()
            val host: String
            var port = fallbackPort
            if (text.startsWith("[")) {
                val end = text.indexOf(']')
                if (end <= 1) {
                    throw IOException("无效的 IPv6 目标地址：$value")
                }
                host = text.substring(1, end)
                if (end + 1 < text.length) {
                    if (text[end + 1] != ':') {
                        throw IOException("无效的目标地址：$value")
                    }
                    port = parsePort(text.substring(end + 2))
                }
            } else {
                val firstColon = text.indexOf(':')
                val lastColon = text.lastIndexOf(':')
                if (firstColon >= 0 && firstColon == lastColon) {
                    host = text.substring(0, firstColon)
                    port = parsePort(text.substring(firstColon + 1))
                } else {
                    host = text
                }
            }
            if (host.isBlank() || port <= 0 || port > 65_535) {
                throw IOException("无效的目标地址：$value")
            }
            return HostPort(host, port)
        }

        fun parsePort(value: String): Int = try {
            value.toInt()
        } catch (exception: NumberFormatException) {
            throw IOException("无效的目标端口：$value", exception)
        }

        fun authorityKey(host: String, port: Int): String =
            host.lowercase(Locale.ROOT) + ':' + port

        fun inputOf(socket: Socket): InputStream? = try {
            socket.getInputStream()
        } catch (ignored: IOException) {
            null
        }

        fun outputOf(socket: Socket): OutputStream? = try {
            socket.getOutputStream()
        } catch (ignored: IOException) {
            null
        }
    }
}
