package io.github.qwqgong.androidcyaml;

import android.os.Process;
import android.util.Log;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Base64;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

/*
 * Loopback-only HTTP CONNECT proxy used to preserve an XHTTP node's configured
 * server address while WebView owns TLS and HTTP. Chromium opens a tunnel for
 * the URL authority, then this proxy dials the exact mihomo server and port.
 * TLS remains end-to-end between WebView and the remote endpoint, so SNI, ALPN
 * and the ClientHello are still generated by System WebView. Unknown
 * authorities are rejected; this is not an open proxy.
 */
final class WebViewConnectProxy implements AutoCloseable {
    private static final String TAG = "AndroidCyaml/WebViewProxy";
    private static final int MAX_LINE_BYTES = 16 * 1024;
    private static final int CONNECT_TIMEOUT_MILLIS = 30_000;
    private static final byte[] IPV4_LOOPBACK = {127, 0, 0, 1};

    private final ServerSocket listener;
    private final ExecutorService workers;
    private final SocketProtector socketProtector;
    private final NetworkRouteProvider routeProvider;
    private final ConcurrentHashMap<String, TargetBinding> bindingsByKey =
            new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, TargetBinding> bindingsByUsername =
            new ConcurrentHashMap<>();
    private final Set<String> authorities = ConcurrentHashMap.newKeySet();
    private final Set<Socket> sockets = ConcurrentHashMap.newKeySet();
    private final AtomicBoolean closed = new AtomicBoolean(false);
    private final String authenticationRealm = "AndroidCyaml-XHTTP-" + UUID.randomUUID();

    WebViewConnectProxy(
            SocketProtector socketProtector,
            NetworkRouteProvider routeProvider
    ) throws IOException {
        this.socketProtector = Objects.requireNonNull(socketProtector);
        this.routeProvider = Objects.requireNonNull(routeProvider);
        listener = new ServerSocket();
        // ProxyConfig below uses this listener address verbatim. Do not use
        // getLoopbackAddress(): Android commonly returns ::1, while a
        // 127.0.0.1 proxy rule cannot reach an IPv6-only ServerSocket.
        listener.bind(new InetSocketAddress(InetAddress.getByAddress(IPV4_LOOPBACK), 0), 64);
        workers = Executors.newCachedThreadPool(new ProxyThreadFactory());
        workers.execute(this::acceptLoop);
    }

    int port() {
        return listener.getLocalPort();
    }

    String authority() {
        return listener.getInetAddress().getHostAddress() + ':' + port();
    }

    TargetBinding register(String urlValue, String serverAddress) throws IOException {
        final URI url;
        try {
            url = URI.create(urlValue);
        } catch (IllegalArgumentException exception) {
            throw new IOException("无效的 WebView XHTTP URL", exception);
        }
        String host = url.getHost();
        if (host == null || host.isBlank()) {
            throw new IOException("WebView XHTTP URL 缺少主机名");
        }
        int port = url.getPort() > 0 ? url.getPort() : 443;
        HostPort target = parseAuthority(serverAddress, port);
        String authority = authorityKey(host, port);
        String bindingKey = authority + '\n' + authorityKey(target.host(), target.port());
        TargetBinding binding = bindingsByKey.computeIfAbsent(
                bindingKey,
                ignored -> new TargetBinding(bindingKey, authority, target)
        );
        bindingsByUsername.putIfAbsent(binding.username(), binding);
        authorities.add(authority);
        return binding;
    }

    boolean isAuthenticationRealm(String realm) {
        return authenticationRealm.equals(realm);
    }

    private void acceptLoop() {
        while (!closed.get()) {
            try {
                Socket client = listener.accept();
                client.setTcpNoDelay(true);
                sockets.add(client);
                workers.execute(() -> handle(client));
            } catch (IOException ignored) {
                // Listener closure and transient accept failures both end this
                // iteration. The loop exits once close() flips the state.
            }
        }
    }

    private void handle(Socket client) {
        Socket upstream = null;
        try {
            BufferedInputStream input = new BufferedInputStream(client.getInputStream());
            OutputStream output = client.getOutputStream();
            String requestLine = readAsciiLine(input);
            if (requestLine == null) {
                return;
            }
            String[] parts = requestLine.split(" ", 3);
            if (parts.length != 3 || !"CONNECT".equalsIgnoreCase(parts[0])) {
                writeFailure(output, 405, "Method Not Allowed");
                return;
            }
            String authority = parts[1];
            String proxyAuthorization = null;
            while (true) {
                String line = readAsciiLine(input);
                if (line == null || line.isEmpty()) {
                    break;
                }
                int separator = line.indexOf(':');
                if (separator > 0
                        && "Proxy-Authorization".equalsIgnoreCase(line.substring(0, separator))) {
                    proxyAuthorization = line.substring(separator + 1).trim();
                }
            }

            HostPort requested = parseAuthority(authority, 443);
            String requestedAuthority = authorityKey(requested.host(), requested.port());
            if (!authorities.contains(requestedAuthority)) {
                writeFailure(output, 403, "Forbidden");
                return;
            }
            TargetBinding binding = authenticatedBinding(
                    requestedAuthority,
                    proxyAuthorization
            );
            if (binding == null) {
                writeAuthenticationRequired(output);
                return;
            }

            try {
                upstream = connectUpstream(binding.target());
                if (binding.connectionLogged.compareAndSet(false, true)) {
                    try {
                        Log.i(TAG, "Exact CONNECT target active: " + binding.targetDescription());
                    } catch (RuntimeException ignored) {
                        // Local JVM tests do not provide android.util.Log.
                    }
                }
            } catch (SocketProtectionException exception) {
                writeFailure(output, 502, "VPN Protect Failed");
                return;
            }
            output.write("HTTP/1.1 200 Connection Established\r\n\r\n"
                    .getBytes(StandardCharsets.US_ASCII));
            output.flush();

            Socket upstreamSocket = upstream;
            workers.execute(() -> copyAndClose(
                    upstreamSocket,
                    client,
                    inputOf(upstreamSocket),
                    outputOf(client)
            ));
            copy(input, upstream.getOutputStream());
        } catch (IOException ignored) {
            // CONNECT tunnels routinely end with one side closing first.
        } finally {
            closeSocket(client);
            closeSocket(upstream);
        }
    }

    private Socket connectUpstream(HostPort destination) throws IOException {
        NetworkRoute route = routeProvider.current();
        if (route == null) {
            throw new IOException("WebView XHTTP 底层网络不可用");
        }

        IOException lastFailure = null;
        final InetAddress[] addresses;
        try {
            addresses = route.resolve(destination.host());
        } catch (IOException exception) {
            throw exception;
        }
        if (addresses == null || addresses.length == 0) {
            throw new IOException("WebView XHTTP 无法解析目标服务器");
        }
        for (InetAddress address : addresses) {
            Socket candidate = new Socket();
            sockets.add(candidate);
            try {
                // Force creation of the socket FD, bind it to the selected
                // non-VPN network, then exempt that exact FD before connect().
                candidate.setTcpNoDelay(true);
                route.bind(candidate);
                if (!protect(candidate)) {
                    throw new SocketProtectionException();
                }
                candidate.connect(
                        new InetSocketAddress(address, destination.port()),
                        CONNECT_TIMEOUT_MILLIS
                );
                return candidate;
            } catch (SocketProtectionException exception) {
                closeSocket(candidate);
                throw exception;
            } catch (IOException exception) {
                lastFailure = exception;
                closeSocket(candidate);
            }
        }
        throw lastFailure == null
                ? new IOException("WebView XHTTP 无法连接目标服务器")
                : lastFailure;
    }

    private void copyAndClose(
            Socket sourceSocket,
            Socket destinationSocket,
            InputStream input,
            OutputStream output
    ) {
        try {
            if (input != null && output != null) {
                copy(input, output);
            }
        } catch (IOException ignored) {
            // CONNECT tunnels routinely end with one side closing first.
        } finally {
            closeSocket(sourceSocket);
            closeSocket(destinationSocket);
        }
    }

    private static void copy(InputStream input, OutputStream output) throws IOException {
        byte[] buffer = new byte[32 * 1024];
        while (true) {
            int count = input.read(buffer);
            if (count < 0) {
                return;
            }
            if (count > 0) {
                output.write(buffer, 0, count);
                output.flush();
            }
        }
    }

    private static String readAsciiLine(InputStream input) throws IOException {
        byte[] buffer = new byte[MAX_LINE_BYTES];
        int length = 0;
        while (length < buffer.length) {
            int value = input.read();
            if (value < 0) {
                return length == 0 ? null : new String(buffer, 0, length, StandardCharsets.US_ASCII);
            }
            if (value == '\n') {
                if (length > 0 && buffer[length - 1] == '\r') {
                    length--;
                }
                return new String(buffer, 0, length, StandardCharsets.US_ASCII);
            }
            buffer[length++] = (byte) value;
        }
        throw new IOException("CONNECT 请求头行过长");
    }

    private static void writeFailure(OutputStream output, int status, String reason)
            throws IOException {
        output.write(("HTTP/1.1 " + status + " " + reason
                + "\r\nConnection: close\r\nContent-Length: 0\r\n\r\n")
                .getBytes(StandardCharsets.US_ASCII));
        output.flush();
    }

    private void writeAuthenticationRequired(OutputStream output) throws IOException {
        output.write(("HTTP/1.1 407 Proxy Authentication Required\r\n"
                + "Proxy-Authenticate: Basic realm=\"" + authenticationRealm + "\"\r\n"
                + "Proxy-Connection: close\r\n"
                + "Connection: close\r\n"
                + "Content-Length: 0\r\n\r\n")
                .getBytes(StandardCharsets.US_ASCII));
        output.flush();
    }

    private TargetBinding authenticatedBinding(
            String requestedAuthority,
            String authorization
    ) {
        if (authorization == null || !authorization.regionMatches(
                true,
                0,
                "Basic ",
                0,
                6
        )) {
            return null;
        }
        final String credentials;
        try {
            credentials = new String(
                    Base64.getDecoder().decode(authorization.substring(6).trim()),
                    StandardCharsets.UTF_8
            );
        } catch (IllegalArgumentException exception) {
            return null;
        }
        int separator = credentials.indexOf(':');
        if (separator <= 0) {
            return null;
        }
        TargetBinding binding = bindingsByUsername.get(credentials.substring(0, separator));
        if (binding == null || !binding.authority().equals(requestedAuthority)) {
            return null;
        }
        byte[] supplied = credentials.substring(separator + 1)
                .getBytes(StandardCharsets.UTF_8);
        byte[] expected = binding.password().getBytes(StandardCharsets.UTF_8);
        return MessageDigest.isEqual(supplied, expected) ? binding : null;
    }

    private boolean protect(Socket socket) {
        try {
            return socketProtector.protect(socket);
        } catch (RuntimeException ignored) {
            return false;
        }
    }

    private static HostPort parseAuthority(String value, int fallbackPort) throws IOException {
        if (value == null || value.isBlank()) {
            throw new IOException("WebView XHTTP 缺少目标服务器地址");
        }
        String text = value.trim();
        String host;
        int port = fallbackPort;
        if (text.startsWith("[")) {
            int end = text.indexOf(']');
            if (end <= 1) {
                throw new IOException("无效的 IPv6 目标地址：" + value);
            }
            host = text.substring(1, end);
            if (end + 1 < text.length()) {
                if (text.charAt(end + 1) != ':') {
                    throw new IOException("无效的目标地址：" + value);
                }
                port = parsePort(text.substring(end + 2));
            }
        } else {
            int firstColon = text.indexOf(':');
            int lastColon = text.lastIndexOf(':');
            if (firstColon >= 0 && firstColon == lastColon) {
                host = text.substring(0, firstColon);
                port = parsePort(text.substring(firstColon + 1));
            } else {
                host = text;
            }
        }
        if (host.isBlank() || port <= 0 || port > 65_535) {
            throw new IOException("无效的目标地址：" + value);
        }
        return new HostPort(host, port);
    }

    private static int parsePort(String value) throws IOException {
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException exception) {
            throw new IOException("无效的目标端口：" + value, exception);
        }
    }

    private static String authorityKey(String host, int port) {
        return host.toLowerCase(Locale.ROOT) + ':' + port;
    }

    private static InputStream inputOf(Socket socket) {
        try {
            return socket.getInputStream();
        } catch (IOException ignored) {
            return null;
        }
    }

    private static OutputStream outputOf(Socket socket) {
        try {
            return socket.getOutputStream();
        } catch (IOException ignored) {
            return null;
        }
    }

    private void closeSocket(Socket socket) {
        if (socket == null) {
            return;
        }
        sockets.remove(socket);
        try {
            socket.close();
        } catch (IOException ignored) {
            // Tunnel teardown is best effort.
        }
    }

    @Override
    public void close() {
        if (!closed.compareAndSet(false, true)) {
            return;
        }
        try {
            listener.close();
        } catch (IOException ignored) {
            // Listener teardown is best effort.
        }
        for (Socket socket : sockets.toArray(new Socket[0])) {
            closeSocket(socket);
        }
        workers.shutdownNow();
        bindingsByKey.clear();
        bindingsByUsername.clear();
        authorities.clear();
    }

    private record HostPort(String host, int port) {}

    static final class TargetBinding {
        private final String key;
        private final String authority;
        private final HostPort target;
        private final String profileName;
        private final String username = UUID.randomUUID().toString();
        private final String password = UUID.randomUUID().toString();
        private final AtomicBoolean connectionLogged = new AtomicBoolean(false);

        TargetBinding(String key, String authority, HostPort target) {
            this.key = key;
            this.authority = authority;
            this.target = target;
            profileName = "androidcyaml-xhttp-" + UUID.nameUUIDFromBytes(
                    key.getBytes(StandardCharsets.UTF_8)
            );
        }

        String key() {
            return key;
        }

        String authority() {
            return authority;
        }

        HostPort target() {
            return target;
        }

        String targetDescription() {
            String host = target.host();
            return (host.indexOf(':') >= 0 ? '[' + host + ']' : host) + ':' + target.port();
        }

        String profileName() {
            return profileName;
        }

        String username() {
            return username;
        }

        String password() {
            return password;
        }

        String authorizationHeader() {
            return "Basic " + Base64.getEncoder().encodeToString(
                    (username + ':' + password).getBytes(StandardCharsets.UTF_8)
            );
        }
    }

    @FunctionalInterface
    interface SocketProtector {
        boolean protect(Socket socket);
    }

    @FunctionalInterface
    interface NetworkRouteProvider {
        NetworkRoute current() throws IOException;
    }

    interface NetworkRoute {
        InetAddress[] resolve(String host) throws IOException;

        void bind(Socket socket) throws IOException;
    }

    private static final class SocketProtectionException extends IOException {}

    private static final class ProxyThreadFactory implements ThreadFactory {
        private final AtomicInteger nextId = new AtomicInteger();

        @Override
        public Thread newThread(Runnable runnable) {
            Thread thread = new Thread(
                    () -> {
                        try {
                            Process.setThreadPriority(Process.THREAD_PRIORITY_DISPLAY);
                        } catch (RuntimeException ignored) {
                            // Local JVM tests do not provide android.os.Process.
                        }
                        runnable.run();
                    },
                    "AndroidCyaml-WebViewProxy-" + nextId.incrementAndGet()
            );
            thread.setDaemon(true);
            return thread;
        }
    }
}
