package io.github.qwqgong.androidcyaml;

import android.annotation.SuppressLint;
import android.content.Context;
import android.net.Network;
import android.net.Uri;
import android.net.VpnService;
import android.os.Handler;
import android.os.HandlerThread;
import android.os.Looper;
import android.os.Process;
import android.util.Base64;
import android.util.Log;
import android.webkit.HttpAuthHandler;
import android.webkit.JavascriptInterface;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.webkit.WebResourceError;
import android.webkit.WebResourceRequest;

import androidx.webkit.ProxyConfig;
import androidx.webkit.ProxyController;
import androidx.webkit.WebMessageCompat;
import androidx.webkit.WebMessagePortCompat;
import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

/**
 * Executes XHTTP HTTP requests through Android System WebView.
 *
 * <p>The mihomo core keeps XHTTP framing, session identifiers and upload-mode
 * semantics. Only the final HTTP request/response is bridged through JNI so TLS,
 * HTTP/2 headers, connection reuse and browser side traffic are generated by
 * the installed WebView Chromium provider.</p>
 */
final class WebViewXhttpDialer implements AutoCloseable {
    static final String TAG = "AndroidCyaml/WebViewXHTTP";
    private static final long START_TIMEOUT_MILLIS = 45_000L;
    private static final long BINARY_BRIDGE_TIMEOUT_MILLIS = 3_000L;
    private static final int BODY_CHUNK_BYTES = 48 * 1024;
    private static final int MAX_RETAINED_ORIGIN_PAGES = 4;
    static final AtomicBoolean DIRECT_RESPONSE_BRIDGE_LOGGED = new AtomicBoolean(false);
    private static final AtomicBoolean DIRECT_CONTROL_BRIDGE_LOGGED = new AtomicBoolean(false);

    private final Handler mainHandler = new Handler(Looper.getMainLooper());
    private final ExecutorService requestBodyExecutor = Executors.newCachedThreadPool(runnable -> {
        Thread thread = new Thread(
                () -> {
                    try {
                        Process.setThreadPriority(Process.THREAD_PRIORITY_DISPLAY);
                    } catch (RuntimeException ignored) {
                        // Local JVM tests do not provide android.os.Process.
                    }
                    runnable.run();
                },
                "AndroidCyaml-WebViewBody"
        );
        thread.setDaemon(true);
        return thread;
    });
    private final boolean binaryBridgeSupported;
    private final HandlerThread messageHandlerThread;
    private final Handler messageHandler;
    private final ConcurrentHashMap<Long, WebViewXhttpTask> tasks = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<Long, WebViewXhttpTask> tasksByRequestBody = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, WebViewXhttpOriginPage> pages = new ConcurrentHashMap<>();
    private final CountDownLatch webViewReady = new CountDownLatch(1);
    private final AtomicBoolean closed = new AtomicBoolean(false);
    private final AtomicBoolean proxyOverrideInstalled = new AtomicBoolean(false);
    private final AtomicReference<WebView> bootstrapWebView = new AtomicReference<>();
    private final WebViewConnectProxy connectProxy;
    private final Context context;
    private volatile String initializationError;
    private volatile boolean requestStreamingSupported;

    WebViewXhttpDialer(
            VpnService vpnService,
            Supplier<Network> underlyingNetworkSupplier
    ) throws IOException {
        Objects.requireNonNull(vpnService);
        Objects.requireNonNull(underlyingNetworkSupplier);
        context = vpnService.getApplicationContext();
        connectProxy = new WebViewConnectProxy(
                vpnService::protect,
                () -> {
                    Network network = underlyingNetworkSupplier.get();
                    if (network == null) {
                        throw new IOException("WebView XHTTP 底层网络不可用");
                    }
                    return new WebViewConnectProxy.NetworkRoute() {
                        @Override
                        public InetAddress[] resolve(String host) throws IOException {
                            return network.getAllByName(host);
                        }

                        @Override
                        public void bind(Socket socket) throws IOException {
                            network.bindSocket(socket);
                        }
                    };
                }
        );
        binaryBridgeSupported = supportsBinaryWebMessages();
        if (binaryBridgeSupported) {
            messageHandlerThread = new HandlerThread(
                    "AndroidCyaml-WebViewMessage",
                    Process.THREAD_PRIORITY_DISPLAY
            );
            messageHandlerThread.start();
            messageHandler = new Handler(messageHandlerThread.getLooper());
        } else {
            messageHandlerThread = null;
            messageHandler = null;
        }
        try {
            if (!WebViewFeature.isFeatureSupported(WebViewFeature.MULTI_PROFILE)) {
                throw new IOException(
                        "System WebView does not support per-target XHTTP profiles"
                );
            }
            Runnable create = this::createBootstrapWebView;
            if (Looper.myLooper() == Looper.getMainLooper()) {
                create.run();
            } else {
                mainHandler.post(create);
            }
            await(webViewReady, 15_000L, "System WebView did not initialize");
            if (bootstrapWebView.get() == null || initializationError != null) {
                throw new IOException(initializationError == null
                        ? "System WebView did not initialize"
                        : initializationError);
            }
            installProxyOverride();
            WebView initialized = bootstrapWebView.getAndSet(null);
            if (Looper.myLooper() == Looper.getMainLooper()) {
                destroyWebView(initialized);
            } else {
                mainHandler.post(() -> destroyWebView(initialized));
            }
            Log.i(TAG, requestStreamingSupported
                    ? "System WebView streaming request bodies are available"
                    : "System WebView stream-up unavailable; using packet-up fallback");
            Log.i(TAG, binaryBridgeSupported
                    ? "System WebView binary message bridge is available"
                    : "System WebView binary message bridge unavailable; using Base64 fallback");
            Log.i(TAG, "System WebView per-target XHTTP profiles are available");
        } catch (IOException | RuntimeException exception) {
            requestBodyExecutor.shutdownNow();
            stopMessageHandlerThread();
            clearProxyOverride();
            connectProxy.close();
            mainHandler.post(() -> destroyWebView(bootstrapWebView.getAndSet(null)));
            if (exception instanceof IOException ioException) {
                throw ioException;
            }
            throw new IOException("Unable to initialize System WebView XHTTP", exception);
        }
    }

    String startRequest(String requestJson, byte[] body) {
        if (closed.get()) {
            return errorResult("System WebView XHTTP dialer is closed");
        }
        final JSONObject metadata;
        final WebViewXhttpOriginPage page;
        try {
            metadata = new JSONObject(requestJson == null ? "{}" : requestJson);
            String url = metadata.optString("url", "");
            String origin = originOf(url);
            WebViewConnectProxy.TargetBinding binding = connectProxy.register(
                    url,
                    metadata.optString("serverAddress", "")
            );
            page = ensureOriginPage(origin, binding);
        } catch (JSONException | IOException exception) {
            Log.w(TAG, "Unable to prepare browser request: " + exception.getMessage());
            return errorResult(exception.getMessage() == null
                    ? "Invalid WebView XHTTP request metadata"
                    : exception.getMessage());
        }

        long id = metadata.optLong("id", 0L);
        if (id <= 0L) {
            releaseOriginPage(page);
            return errorResult("System WebView received an invalid request id");
        }
        long bodyId = metadata.optLong("bodyId", 0L);
        if (bodyId < 0L || (bodyId > 0L && !requestStreamingSupported)) {
            if (bodyId > 0L) {
                MihomoNative.closeBrowserRequestBody(bodyId);
            }
            releaseOriginPage(page);
            return errorResult("System WebView does not support streaming request bodies");
        }
        WebViewXhttpTask task = new WebViewXhttpTask(
                id,
                body == null ? new byte[0] : body.clone(),
                bodyId,
                page,
                () -> {
                    if (bodyId > 0L) {
                        tasksByRequestBody.remove(bodyId);
                    }
                    releaseOriginPage(page);
                }
        );
        if (tasks.putIfAbsent(id, task) != null) {
            task.discard();
            return errorResult("System WebView received a duplicate request id");
        }
        if (bodyId > 0L) {
            tasksByRequestBody.put(bodyId, task);
        }

        dispatchRequestStart(page, task, metadata.toString());

        try {
            return new JSONObject().put("id", id).toString();
        } catch (JSONException impossible) {
            closeRequest(id);
            return errorResult("Unable to encode System WebView request id");
        }
    }

    String awaitResponse(long id) {
        WebViewXhttpTask task = tasks.get(id);
        if (task == null) {
            return errorResult("System WebView XHTTP request is unavailable");
        }
        try {
            boolean ready;
            if (task.requestBodyId > 0L) {
                task.headersReady.await();
                ready = true;
            } else {
                ready = task.headersReady.await(START_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS);
            }
            if (!ready) {
                closeRequest(id);
                return errorResult("System WebView XHTTP response header timeout");
            }
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            closeRequest(id);
            return errorResult("System WebView XHTTP request interrupted");
        }

        if (task.error != null) {
            Log.w(TAG, "Browser request failed: " + task.error);
            tasks.remove(id);
            return errorResult(task.error);
        }
        try {
            JSONObject result = new JSONObject();
            result.put("status", task.statusCode);
            result.put("statusText", task.statusText == null ? "" : task.statusText);
            result.put("headers", new JSONObject(task.headersJson == null ? "{}" : task.headersJson));
            return result.toString();
        } catch (JSONException exception) {
            closeRequest(id);
            return errorResult("Unable to encode System WebView response headers");
        }
    }

    boolean supportsRequestStreaming() {
        return requestStreamingSupported;
    }

    int readResponse(long id, byte[] destination) {
        // New cores receive WebView response chunks through direct JNI pushes.
        return -1;
    }

    void closeRequest(long id) {
        WebViewXhttpTask task = tasks.remove(id);
        if (task == null) {
            return;
        }
        mainHandler.post(() -> {
            WebView current = task.page.webView;
            if (current != null) {
                current.evaluateJavascript("window.androidCyamlCancel(" + id + ");", null);
            }
        });
        task.close();
    }

    @Override
    public void close() {
        if (!closed.compareAndSet(false, true)) {
            return;
        }
        tasks.forEach((id, task) -> task.close());
        tasks.clear();
        tasksByRequestBody.clear();
        requestBodyExecutor.shutdownNow();
        stopMessageHandlerThread();
        clearProxyOverride();
        connectProxy.close();
        mainHandler.post(() -> {
            destroyWebView(bootstrapWebView.getAndSet(null));
            for (WebViewXhttpOriginPage page : pages.values()) {
                page.closeMessagePort();
                destroyWebView(page.webView);
                page.webView = null;
            }
            pages.clear();
        });
    }

    private void createBootstrapWebView() {
        if (closed.get()) {
            initializationError = "System WebView XHTTP was closed during startup";
            webViewReady.countDown();
            return;
        }
        try {
            WebView created = newWebView(null);
            created.addJavascriptInterface(new JavascriptBridge(null), "AndroidCyamlNative");
            created.setWebViewClient(new WebViewClient() {
                @Override
                public void onReceivedError(
                        WebView view,
                        WebResourceRequest request,
                        WebResourceError error
                ) {
                    if (request == null || request.isForMainFrame()) {
                        initializationError = "Unable to initialize System WebView capability page";
                        webViewReady.countDown();
                    }
                }
            });
            bootstrapWebView.set(created);
            created.loadDataWithBaseURL(
                    "https://androidcyaml.invalid/",
                    WebViewXhttpBridgeScript.SOURCE,
                    "text/html",
                    StandardCharsets.UTF_8.name(),
                    null
            );
        } catch (RuntimeException exception) {
            initializationError = "Unable to create System WebView XHTTP dialer: "
                    + (exception.getMessage() == null
                    ? exception.getClass().getSimpleName()
                    : exception.getMessage());
            Log.e(TAG, initializationError, exception);
            webViewReady.countDown();
        }
    }

    private WebViewXhttpOriginPage ensureOriginPage(
            String origin,
            WebViewConnectProxy.TargetBinding binding
    ) throws IOException {
        WebViewXhttpOriginPage page = pages.compute(
                binding.key(),
                (ignored, existing) -> {
                    WebViewXhttpOriginPage selected = existing == null
                            ? new WebViewXhttpOriginPage(origin, binding)
                            : existing;
                    selected.retain();
                    return selected;
                }
        );
        if (page.initializationStarted.compareAndSet(false, true)) {
            mainHandler.post(() -> initializeOriginPage(page));
        }
        try {
            await(page.ready, 15_000L, "System WebView XHTTP page did not initialize");
            if (page.error != null) {
                throw new IOException(page.error);
            }
            return page;
        } catch (IOException exception) {
            releaseOriginPage(page);
            throw exception;
        }
    }

    @SuppressLint({"SetJavaScriptEnabled", "AddJavascriptInterface"})
    private WebView newWebView(String profileName) {
        WebView created = new WebView(context);
        if (profileName != null) {
            WebViewCompat.setProfile(created, profileName);
        }
        created.setRendererPriorityPolicy(WebView.RENDERER_PRIORITY_IMPORTANT, false);
        WebSettings settings = created.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(false);
        settings.setAllowFileAccess(false);
        settings.setAllowContentAccess(false);
        settings.setCacheMode(WebSettings.LOAD_DEFAULT);
        settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);
        return created;
    }

    @SuppressLint("AddJavascriptInterface")
    private void initializeOriginPage(WebViewXhttpOriginPage page) {
        if (closed.get()) {
            page.fail("System WebView is unavailable");
            return;
        }
        try {
            WebView current = newWebView(page.binding.profileName());
            current.addJavascriptInterface(
                    new JavascriptBridge(page),
                    "AndroidCyamlNative"
            );
            current.setWebViewClient(new WebViewClient() {
                @Override
                public void onReceivedHttpAuthRequest(
                        WebView view,
                        HttpAuthHandler handler,
                        String host,
                        String realm
                ) {
                    if (connectProxy.isAuthenticationRealm(realm)) {
                        handler.proceed(
                                page.binding.username(),
                                page.binding.password()
                        );
                    } else {
                        handler.cancel();
                    }
                }

                @Override
                public void onReceivedError(
                        WebView view,
                        WebResourceRequest request,
                        WebResourceError error
                ) {
                    // Fetch failures are reported with their task id by the
                    // JavaScript bridge below. Only log a page-load failure
                    // here; canceled health checks otherwise flood warning
                    // logs with context-free net::ERR_FAILED entries.
                    if (request == null || request.isForMainFrame()) {
                        Log.w(
                                TAG,
                                "Chromium page error "
                                        + (error == null ? "unknown" : error.getErrorCode())
                                        + ": "
                                        + (error == null ? "unknown" : error.getDescription())
                        );
                    }
                }
            });
            page.webView = current;
            current.loadDataWithBaseURL(
                    page.origin + "/",
                    originPageSource(),
                    "text/html",
                    StandardCharsets.UTF_8.name(),
                    null
            );
        } catch (RuntimeException exception) {
            page.fail(
                    "Unable to load System WebView XHTTP origin: "
                            + (exception.getMessage() == null
                            ? exception.getClass().getSimpleName()
                            : exception.getMessage())
            );
        }
    }

    private static String originPageSource() {
        return WebViewXhttpBridgeScript.SOURCE.replace(
                "<meta charset=\"utf-8\">",
                "<meta charset=\"utf-8\">\n<link rel=\"preconnect\" href=\"/\">"
        );
    }

    private void installBinaryBridge(WebViewXhttpOriginPage page) {
        if (closed.get() || page.webView == null) {
            page.fail("System WebView is unavailable");
            return;
        }
        WebMessagePortCompat[] channel = null;
        boolean transferred = false;
        try {
            channel = WebViewCompat.createWebMessageChannel(page.webView);
            if (channel == null || channel.length != 2) {
                throw new IllegalStateException("WebView returned an invalid message channel");
            }
            WebMessagePortCompat applicationPort = channel[0];
            applicationPort.setWebMessageCallback(
                    messageHandler,
                    new WebMessagePortCompat.WebMessageCallbackCompat() {
                        @Override
                        public void onMessage(
                                WebMessagePortCompat port,
                                WebMessageCompat message
                        ) {
                            handleBinaryBridgeMessage(page, message);
                        }
                    }
            );
            page.messagePort.set(applicationPort);
            WebViewCompat.postWebMessage(
                    page.webView,
                    new WebMessageCompat(
                            "androidcyaml-binary-v1",
                            new WebMessagePortCompat[]{channel[1]}
                    ),
                    Uri.parse(page.origin)
            );
            transferred = true;
            mainHandler.postDelayed(() -> {
                if (page.resolveBridge(false)) {
                    page.closeMessagePort();
                    disableBinaryBridgeInPage(page);
                    Log.w(TAG, "WebView binary message bridge timed out; using Base64 fallback");
                }
            }, BINARY_BRIDGE_TIMEOUT_MILLIS);
        } catch (RuntimeException exception) {
            page.closeMessagePort();
            if (channel != null) {
                WebViewXhttpOriginPage.closeMessagePort(channel[0]);
                if (!transferred) {
                    WebViewXhttpOriginPage.closeMessagePort(channel[1]);
                }
            }
            if (page.resolveBridge(false)) {
                disableBinaryBridgeInPage(page);
                Log.w(TAG, "Unable to initialize WebView binary message bridge; using Base64 fallback", exception);
            }
        }
    }

    private void handleBinaryBridgeMessage(WebViewXhttpOriginPage page, WebMessageCompat message) {
        if (closed.get() || message == null
                || message.getType() != WebMessageCompat.TYPE_ARRAY_BUFFER) {
            return;
        }
        WebViewBinaryBridge.ResponseFrame responseFrame =
                WebViewBinaryBridge.decodeResponseFrame(message.getArrayBuffer());
        if (responseFrame == null) {
            Log.w(TAG, "Ignoring malformed WebView binary response frame");
            return;
        }
        WebViewXhttpTask task = tasks.get(responseFrame.requestId());
        if (task == null || task.page != page) {
            return;
        }
        switch (responseFrame.type()) {
            case WebViewBinaryBridge.TYPE_RESPONSE_CHUNK -> task.data(responseFrame.data());
            case WebViewBinaryBridge.TYPE_RESPONSE_COMPLETE -> task.complete();
            case WebViewBinaryBridge.TYPE_RESPONSE_ERROR -> task.fail(
                    responseFrame.error().isBlank()
                            ? "System WebView fetch failed"
                            : responseFrame.error()
            );
            case WebViewBinaryBridge.TYPE_RESPONSE_HEADERS ->
                    handleBinaryResponseHeaders(task, responseFrame.data());
            default -> {
                // decodeResponseFrame filters unknown message types.
            }
        }
    }

    private void handleBinaryResponseHeaders(WebViewXhttpTask task, byte[] payload) {
        try {
            JSONObject response = new JSONObject(new String(payload, StandardCharsets.UTF_8));
            int status = response.optInt("status", 0);
            JSONObject headers = response.optJSONObject("headers");
            if (status <= 0 || headers == null) {
                throw new JSONException("Invalid response headers");
            }
            task.headers(
                    status,
                    response.optString("statusText", ""),
                    headers.toString()
            );
        } catch (JSONException exception) {
            task.fail("Invalid response headers from System WebView");
        }
    }

    private void releaseOriginPage(WebViewXhttpOriginPage page) {
        page.release();
        mainHandler.post(this::trimIdleOriginPages);
    }

    private void trimIdleOriginPages() {
        int excess = pages.size() - MAX_RETAINED_ORIGIN_PAGES;
        if (excess <= 0) {
            return;
        }
        List<WebViewXhttpOriginPage> idle = new ArrayList<>();
        for (WebViewXhttpOriginPage candidate : pages.values()) {
            if (candidate.activeRequests.get() == 0) {
                idle.add(candidate);
            }
        }
        idle.sort(Comparator.comparingLong(page -> page.lastUsedNanos));
        for (WebViewXhttpOriginPage candidate : idle) {
            if (excess <= 0) {
                break;
            }
            AtomicBoolean removed = new AtomicBoolean(false);
            pages.computeIfPresent(candidate.binding.key(), (ignored, current) -> {
                if (current == candidate && current.activeRequests.get() == 0) {
                    removed.set(true);
                    return null;
                }
                return current;
            });
            if (removed.get()) {
                candidate.closeMessagePort();
                destroyWebView(candidate.webView);
                candidate.webView = null;
                connectProxy.unregister(candidate.binding);
                excess--;
            }
        }
    }

    private void dispatchRequestStart(WebViewXhttpOriginPage page, WebViewXhttpTask task, String metadataJson) {
        mainHandler.post(() -> dispatchRequestStartOnMain(page, task, metadataJson));
    }

    private void dispatchRequestStartOnMain(
            WebViewXhttpOriginPage page,
            WebViewXhttpTask task,
            String metadataJson
    ) {
        if (closed.get() || tasks.get(task.id) != task || task.closed.get()) {
            return;
        }
        WebMessagePortCompat port = page.messagePort.get();
        if (page.binaryBridge.get() && port != null) {
            try {
                port.postMessage(new WebMessageCompat(
                        WebViewBinaryBridge.encodeRequestStart(metadataJson)
                ));
                if (DIRECT_CONTROL_BRIDGE_LOGGED.compareAndSet(false, true)) {
                    Log.i(TAG, "Direct WebMessage XHTTP control bridge is active");
                }
                return;
            } catch (RuntimeException exception) {
                if (page.disableBinaryBridge()) {
                    disableBinaryBridgeInPage(page);
                    Log.w(TAG, "WebView control bridge failed; using JavaScript fallback", exception);
                }
            }
        }
        WebView current = page.webView;
        if (current == null || closed.get()) {
            task.fail("System WebView is unavailable");
            return;
        }
        current.evaluateJavascript(
                "window.androidCyamlStart(" + JSONObject.quote(metadataJson) + ");",
                null
        );
    }

    private static boolean supportsBinaryWebMessages() {
        return WebViewFeature.isFeatureSupported(WebViewFeature.CREATE_WEB_MESSAGE_CHANNEL)
                && WebViewFeature.isFeatureSupported(WebViewFeature.POST_WEB_MESSAGE)
                && WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_PORT_POST_MESSAGE)
                && WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK)
                && WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_ARRAY_BUFFER);
    }

    private void stopMessageHandlerThread() {
        if (messageHandlerThread != null) {
            messageHandlerThread.quitSafely();
        }
    }

    private void disableBinaryBridgeInPage(WebViewXhttpOriginPage page) {
        mainHandler.post(() -> {
            WebView current = page.webView;
            if (current != null && !closed.get()) {
                current.evaluateJavascript("window.androidCyamlDisableBinaryBridge();", null);
            }
        });
    }

    private static void destroyWebView(WebView current) {
        if (current == null) {
            return;
        }
        current.stopLoading();
        current.removeJavascriptInterface("AndroidCyamlNative");
        current.setWebViewClient(null);
        current.destroy();
    }

    static String originOf(String urlValue) throws IOException {
        final URI uri;
        try {
            uri = URI.create(urlValue == null ? "" : urlValue);
        } catch (IllegalArgumentException exception) {
            throw new IOException("Invalid System WebView XHTTP URL", exception);
        }
        if (!"https".equalsIgnoreCase(uri.getScheme())
                || uri.getHost() == null
                || uri.getHost().isBlank()
                || uri.getUserInfo() != null) {
            throw new IOException("System WebView XHTTP only accepts HTTPS origin URLs");
        }
        String host = uri.getHost().toLowerCase(Locale.ROOT);
        if (host.indexOf(':') >= 0
                && !(host.startsWith("[") && host.endsWith("]"))) {
            host = '[' + host + ']';
        }
        int port = uri.getPort();
        return "https://" + host + (port > 0 && port != 443 ? ":" + port : "");
    }

    private void installProxyOverride() throws IOException {
        if (!WebViewFeature.isFeatureSupported(WebViewFeature.PROXY_OVERRIDE)) {
            throw new IOException("当前 Android System WebView 不支持进程级代理覆写");
        }
        ProxyConfig proxyConfig = new ProxyConfig.Builder()
                .addProxyRule(connectProxy.authority())
                .build();
        CountDownLatch applied = new CountDownLatch(1);
        try {
            ProxyController.getInstance().setProxyOverride(
                    proxyConfig,
                    Runnable::run,
                    applied::countDown
            );
        } catch (IllegalArgumentException | UnsupportedOperationException exception) {
            throw new IOException("无法配置 System WebView CONNECT 代理", exception);
        }
        await(applied, 10_000L, "System WebView CONNECT 代理应用超时");
        proxyOverrideInstalled.set(true);
    }

    private void clearProxyOverride() {
        if (!proxyOverrideInstalled.compareAndSet(true, false)) {
            return;
        }
        try {
            ProxyController.getInstance().clearProxyOverride(
                    Runnable::run,
                    () -> {}
            );
        } catch (RuntimeException exception) {
            Log.w(TAG, "Unable to clear System WebView proxy override", exception);
        }
    }

    private static void await(CountDownLatch latch, long timeout, String message) throws IOException {
        try {
            if (!latch.await(timeout, TimeUnit.MILLISECONDS)) {
                throw new IOException(message);
            }
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new IOException(message, exception);
        }
    }

    private static String errorResult(String message) {
        try {
            return new JSONObject().put("error", message == null ? "System WebView XHTTP failed" : message).toString();
        } catch (JSONException impossible) {
            return "{\"error\":\"System WebView XHTTP failed\"}";
        }
    }

    private void dispatchRequestBodyChunk(
            WebViewXhttpOriginPage page,
            WebViewXhttpTask task,
            long bodyId,
            long readId,
            int status,
            byte[] chunk,
            int count
    ) {
        mainHandler.post(() -> dispatchRequestBodyChunkOnMain(
                page,
                task,
                bodyId,
                readId,
                status,
                chunk,
                count
        ));
    }

    private void dispatchRequestBodyChunkOnMain(
            WebViewXhttpOriginPage page,
            WebViewXhttpTask task,
            long bodyId,
            long readId,
            int status,
            byte[] chunk,
            int count
    ) {
        if (closed.get() || page == null || page.webView == null) {
            return;
        }
        if (task != null && (tasksByRequestBody.get(bodyId) != task
                || task.requestBodyClosed.get())) {
            return;
        }
        WebMessagePortCompat port = page.messagePort.get();
        if (page.binaryBridge.get() && port != null) {
            try {
                port.postMessage(new WebMessageCompat(
                        WebViewBinaryBridge.encodeRequestBodyChunk(
                                bodyId,
                                readId,
                                status,
                                chunk,
                                count
                        )
                ));
                return;
            } catch (RuntimeException exception) {
                if (page.disableBinaryBridge()) {
                    disableBinaryBridgeInPage(page);
                    Log.w(TAG, "WebView binary message bridge failed; using Base64 fallback", exception);
                }
            }
        }
        String encoded = status > 0 && chunk != null && count > 0
                ? Base64.encodeToString(chunk, 0, count, Base64.NO_WRAP)
                : "";
        page.webView.evaluateJavascript(
                "window.androidCyamlBodyChunk("
                        + bodyId + ","
                        + readId + ","
                        + status + ","
                        + JSONObject.quote(encoded == null ? "" : encoded)
                        + ");",
                null
        );
    }

    private final class JavascriptBridge {
        private final WebViewXhttpOriginPage page;

        JavascriptBridge(WebViewXhttpOriginPage page) {
            this.page = page;
        }

        @JavascriptInterface
        public void onReady(boolean supportsRequestStreaming) {
            if (page == null) {
                requestStreamingSupported = supportsRequestStreaming;
                webViewReady.countDown();
                return;
            }
            if (supportsRequestStreaming != requestStreamingSupported) {
                page.fail("System WebView request-stream capability changed during startup");
                return;
            }
            if (!binaryBridgeSupported) {
                page.resolveBridge(false);
                return;
            }
            if (page.bridgeInstallationStarted.compareAndSet(false, true)) {
                mainHandler.post(() -> installBinaryBridge(page));
            }
        }

        @JavascriptInterface
        public void onMessagePortReady() {
            if (page == null) {
                return;
            }
            if (page.resolveBridge(true)) {
                Log.i(TAG, "WebView binary message bridge is active for " + page.origin);
            } else if (!page.binaryBridge.get()) {
                page.closeMessagePort();
                disableBinaryBridgeInPage(page);
            }
        }

        @JavascriptInterface
        public int requestBodyLength(long id) {
            WebViewXhttpTask task = tasks.get(id);
            return task == null ? 0 : task.requestBody.length;
        }

        @JavascriptInterface
        public String requestBodyChunk(long id, int offset, int maximum) {
            WebViewXhttpTask task = tasks.get(id);
            if (task == null || offset < 0 || offset >= task.requestBody.length) {
                return "";
            }
            int length = Math.min(Math.min(Math.max(maximum, 1), BODY_CHUNK_BYTES), task.requestBody.length - offset);
            return Base64.encodeToString(
                    Arrays.copyOfRange(task.requestBody, offset, offset + length),
                    Base64.NO_WRAP
            );
        }

        @JavascriptInterface
        public void readRequestBodyChunk(long bodyId, long readId, int maximum) {
            WebViewXhttpTask task = tasksByRequestBody.get(bodyId);
            if (page == null || bodyId <= 0L || readId <= 0L || closed.get()
                    || task == null || task.page != page || task.requestBodyClosed.get()) {
                dispatchRequestBodyChunk(page, null, bodyId, readId, -1, null, 0);
                return;
            }
            int capacity = Math.min(Math.max(maximum, 1), BODY_CHUNK_BYTES);
            try {
                requestBodyExecutor.execute(() -> {
                    try {
                        byte[] chunk = new byte[capacity];
                        int count = MihomoNative.readBrowserRequestBody(bodyId, chunk);
                        if (tasksByRequestBody.get(bodyId) != task
                                || task.requestBodyClosed.get()
                                || closed.get()) {
                            return;
                        }
                        if (count < 0 || count > capacity) {
                            dispatchRequestBodyChunk(page, task, bodyId, readId, -1, null, 0);
                        } else if (count == 0) {
                            dispatchRequestBodyChunk(page, task, bodyId, readId, 0, null, 0);
                        } else {
                            dispatchRequestBodyChunk(
                                    page,
                                    task,
                                    bodyId,
                                    readId,
                                    1,
                                    chunk,
                                    count
                            );
                        }
                    } catch (RuntimeException exception) {
                        Log.w(TAG, "Unable to read WebView request body", exception);
                        dispatchRequestBodyChunk(page, task, bodyId, readId, -1, null, 0);
                    }
                });
            } catch (RejectedExecutionException exception) {
                dispatchRequestBodyChunk(page, task, bodyId, readId, -1, null, 0);
            }
        }

        @JavascriptInterface
        public void closeRequestBody(long bodyId) {
            MihomoNative.closeBrowserRequestBody(bodyId);
        }

        @JavascriptInterface
        public void onHeaders(long id, int status, String statusText, String headersJson) {
            WebViewXhttpTask task = tasks.get(id);
            if (task != null) {
                task.headers(status, statusText, headersJson);
            }
        }

        @JavascriptInterface
        public void onChunk(long id, String encoded) {
            WebViewXhttpTask task = tasks.get(id);
            if (task == null || encoded == null || encoded.isEmpty()) {
                return;
            }
            try {
                task.data(Base64.decode(encoded, Base64.DEFAULT));
            } catch (IllegalArgumentException exception) {
                task.fail("Invalid response chunk from System WebView");
            }
        }

        @JavascriptInterface
        public void onComplete(long id) {
            WebViewXhttpTask task = tasks.get(id);
            if (task != null) {
                task.complete();
            }
        }

        @JavascriptInterface
        public void onError(long id, String message) {
            WebViewXhttpTask task = tasks.get(id);
            if (task != null) {
                Log.w(TAG, "Chromium fetch failed: " + message);
                task.fail(message == null || message.isBlank()
                        ? "System WebView fetch failed"
                        : message);
            }
        }
    }

}
