package io.github.qwqgong.androidcyaml

import android.annotation.SuppressLint
import android.content.Context
import android.net.Network
import android.net.Uri
import android.net.VpnService
import android.os.Handler
import android.os.HandlerThread
import android.os.Looper
import android.os.Process
import android.util.Base64
import android.util.Log
import android.webkit.HttpAuthHandler
import android.webkit.JavascriptInterface
import android.webkit.WebResourceError
import android.webkit.WebResourceRequest
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.webkit.ProxyConfig
import androidx.webkit.ProxyController
import androidx.webkit.WebMessageCompat
import androidx.webkit.WebMessagePortCompat
import androidx.webkit.WebViewCompat
import androidx.webkit.WebViewFeature
import org.json.JSONException
import org.json.JSONObject
import java.io.IOException
import java.net.InetAddress
import java.net.Socket
import java.net.URI
import java.nio.charset.StandardCharsets
import java.util.Locale
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.CountDownLatch
import java.util.concurrent.Executors
import java.util.concurrent.RejectedExecutionException
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicReference

/**
 * Executes XHTTP HTTP requests through Android System WebView.
 *
 * The mihomo core keeps XHTTP framing, session identifiers and upload-mode
 * semantics. Only the final HTTP request/response is bridged through JNI so TLS,
 * HTTP/2 headers, connection reuse and browser side traffic are generated by
 * the installed WebView Chromium provider.
 */
class WebViewXhttpDialer(
    vpnService: VpnService,
    underlyingNetworkSupplier: () -> Network?,
) : AutoCloseable {
    private val mainHandler = Handler(Looper.getMainLooper())
    private val requestBodyExecutor = Executors.newCachedThreadPool { runnable ->
        val thread = Thread(
            {
                try {
                    Process.setThreadPriority(Process.THREAD_PRIORITY_DISPLAY)
                } catch (ignored: RuntimeException) {
                    // Local JVM tests do not provide android.os.Process.
                }
                runnable.run()
            },
            "AndroidCyaml-WebViewBody",
        )
        thread.isDaemon = true
        thread
    }
    private val binaryBridgeSupported: Boolean
    private val messageHandlerThread: HandlerThread?
    private val messageHandler: Handler?
    private val tasks = ConcurrentHashMap<Long, WebViewXhttpTask>()
    private val tasksByRequestBody = ConcurrentHashMap<Long, WebViewXhttpTask>()
    private val pages = ConcurrentHashMap<String, WebViewXhttpOriginPage>()
    private val webViewReady = CountDownLatch(1)
    private val closed = AtomicBoolean(false)
    private val proxyOverrideInstalled = AtomicBoolean(false)
    private val bootstrapWebView = AtomicReference<WebView?>()
    private val connectProxy: WebViewConnectProxy
    private val context: Context = vpnService.applicationContext

    @Volatile
    private var initializationError: String? = null

    @Volatile
    private var requestStreamingSupported = false

    init {
        connectProxy = WebViewConnectProxy(
            { socket -> vpnService.protect(socket) },
            {
                val network = underlyingNetworkSupplier()
                    ?: throw IOException("WebView XHTTP 底层网络不可用")
                object : WebViewConnectProxy.NetworkRoute {
                    override fun resolve(host: String): Array<InetAddress> =
                        network.getAllByName(host)

                    override fun bind(socket: Socket) {
                        network.bindSocket(socket)
                    }
                }
            },
        )
        binaryBridgeSupported = supportsBinaryWebMessages()
        if (binaryBridgeSupported) {
            messageHandlerThread = HandlerThread(
                "AndroidCyaml-WebViewMessage",
                Process.THREAD_PRIORITY_DISPLAY,
            )
            messageHandlerThread.start()
            messageHandler = Handler(messageHandlerThread.looper)
        } else {
            messageHandlerThread = null
            messageHandler = null
        }
        try {
            if (!WebViewFeature.isFeatureSupported(WebViewFeature.MULTI_PROFILE)) {
                throw IOException("System WebView does not support per-target XHTTP profiles")
            }
            val create = Runnable { createBootstrapWebView() }
            if (Looper.myLooper() == Looper.getMainLooper()) {
                create.run()
            } else {
                mainHandler.post(create)
            }
            await(webViewReady, 15_000L, "System WebView did not initialize")
            if (bootstrapWebView.get() == null || initializationError != null) {
                throw IOException(initializationError ?: "System WebView did not initialize")
            }
            installProxyOverride()
            val initialized = bootstrapWebView.getAndSet(null)
            if (Looper.myLooper() == Looper.getMainLooper()) {
                destroyWebView(initialized)
            } else {
                mainHandler.post { destroyWebView(initialized) }
            }
            Log.i(
                TAG,
                if (requestStreamingSupported) {
                    "System WebView streaming request bodies are available"
                } else {
                    "System WebView stream-up unavailable; using packet-up fallback"
                },
            )
            Log.i(
                TAG,
                if (binaryBridgeSupported) {
                    "System WebView binary message bridge is available"
                } else {
                    "System WebView binary message bridge unavailable; using Base64 fallback"
                },
            )
            Log.i(TAG, "System WebView per-target XHTTP profiles are available")
        } catch (exception: IOException) {
            abandonFailedStartup()
            throw exception
        } catch (exception: RuntimeException) {
            abandonFailedStartup()
            throw IOException("Unable to initialize System WebView XHTTP", exception)
        }
    }

    private fun abandonFailedStartup() {
        requestBodyExecutor.shutdownNow()
        stopMessageHandlerThread()
        clearProxyOverride()
        connectProxy.close()
        mainHandler.post { destroyWebView(bootstrapWebView.getAndSet(null)) }
    }

    fun startRequest(requestJson: String?, body: ByteArray?): String {
        if (closed.get()) {
            return errorResult("System WebView XHTTP dialer is closed")
        }
        val metadata: JSONObject
        val page: WebViewXhttpOriginPage
        try {
            metadata = JSONObject(requestJson ?: "{}")
            val url = metadata.optString("url", "")
            val origin = originOf(url)
            val binding = connectProxy.register(url, metadata.optString("serverAddress", ""))
            page = ensureOriginPage(origin, binding)
        } catch (exception: JSONException) {
            return failedPreparation(exception)
        } catch (exception: IOException) {
            return failedPreparation(exception)
        }

        val id = metadata.optLong("id", 0L)
        if (id <= 0L) {
            releaseOriginPage(page)
            return errorResult("System WebView received an invalid request id")
        }
        val bodyId = metadata.optLong("bodyId", 0L)
        if (bodyId < 0L || (bodyId > 0L && !requestStreamingSupported)) {
            if (bodyId > 0L) {
                MihomoNative.closeBrowserRequestBody(bodyId)
            }
            releaseOriginPage(page)
            return errorResult("System WebView does not support streaming request bodies")
        }
        val task = WebViewXhttpTask(
            id,
            body?.clone() ?: ByteArray(0),
            bodyId,
            page,
            {
                if (bodyId > 0L) {
                    tasksByRequestBody.remove(bodyId)
                }
                releaseOriginPage(page)
            },
        )
        if (tasks.putIfAbsent(id, task) != null) {
            task.discard()
            return errorResult("System WebView received a duplicate request id")
        }
        if (bodyId > 0L) {
            tasksByRequestBody[bodyId] = task
        }

        dispatchRequestStart(page, task, metadata.toString())

        return try {
            JSONObject().put("id", id).toString()
        } catch (impossible: JSONException) {
            closeRequest(id)
            errorResult("Unable to encode System WebView request id")
        }
    }

    private fun failedPreparation(exception: Exception): String {
        Log.w(TAG, "Unable to prepare browser request: " + exception.message)
        return errorResult(exception.message ?: "Invalid WebView XHTTP request metadata")
    }

    fun awaitResponse(id: Long): String {
        val task = tasks[id] ?: return errorResult("System WebView XHTTP request is unavailable")
        try {
            val ready = if (task.requestBodyId > 0L) {
                task.headersReady.await()
                true
            } else {
                task.headersReady.await(START_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)
            }
            if (!ready) {
                closeRequest(id)
                return errorResult("System WebView XHTTP response header timeout")
            }
        } catch (exception: InterruptedException) {
            Thread.currentThread().interrupt()
            closeRequest(id)
            return errorResult("System WebView XHTTP request interrupted")
        }

        val failure = task.error
        if (failure != null) {
            Log.w(TAG, "Browser request failed: $failure")
            tasks.remove(id)
            return errorResult(failure)
        }
        return try {
            val result = JSONObject()
            result.put("status", task.statusCode)
            result.put("statusText", task.statusText ?: "")
            result.put("headers", JSONObject(task.headersJson ?: "{}"))
            result.toString()
        } catch (exception: JSONException) {
            closeRequest(id)
            errorResult("Unable to encode System WebView response headers")
        }
    }

    fun supportsRequestStreaming(): Boolean = requestStreamingSupported

    fun readResponse(id: Long, destination: ByteArray?): Int {
        // New cores receive WebView response chunks through direct JNI pushes.
        return -1
    }

    fun closeRequest(id: Long) {
        val task = tasks.remove(id) ?: return
        mainHandler.post {
            task.page.webView?.evaluateJavascript("window.androidCyamlCancel($id);", null)
        }
        task.close()
    }

    override fun close() {
        if (!closed.compareAndSet(false, true)) {
            return
        }
        tasks.forEach { (_, task) -> task.close() }
        tasks.clear()
        tasksByRequestBody.clear()
        requestBodyExecutor.shutdownNow()
        stopMessageHandlerThread()
        clearProxyOverride()
        connectProxy.close()
        mainHandler.post {
            destroyWebView(bootstrapWebView.getAndSet(null))
            for (page in pages.values) {
                page.closeMessagePort()
                destroyWebView(page.webView)
                page.webView = null
            }
            pages.clear()
        }
    }

    private fun createBootstrapWebView() {
        if (closed.get()) {
            initializationError = "System WebView XHTTP was closed during startup"
            webViewReady.countDown()
            return
        }
        try {
            val created = newWebView(null)
            created.addJavascriptInterface(JavascriptBridge(null), "AndroidCyamlNative")
            created.webViewClient = object : WebViewClient() {
                override fun onReceivedError(
                    view: WebView,
                    request: WebResourceRequest,
                    error: WebResourceError,
                ) {
                    if (request.isForMainFrame) {
                        initializationError =
                            "Unable to initialize System WebView capability page"
                        webViewReady.countDown()
                    }
                }
            }
            bootstrapWebView.set(created)
            created.loadDataWithBaseURL(
                "https://androidcyaml.invalid/",
                WebViewXhttpBridgeScript.SOURCE,
                "text/html",
                StandardCharsets.UTF_8.name(),
                null,
            )
        } catch (exception: RuntimeException) {
            val message = "Unable to create System WebView XHTTP dialer: " +
                (exception.message ?: exception.javaClass.simpleName)
            initializationError = message
            Log.e(TAG, message, exception)
            webViewReady.countDown()
        }
    }

    private fun ensureOriginPage(
        origin: String,
        binding: WebViewConnectProxy.TargetBinding,
    ): WebViewXhttpOriginPage {
        val page = pages.compute(binding.key()) { _, existing ->
            val selected = existing ?: WebViewXhttpOriginPage(origin, binding)
            selected.retain()
            selected
        }!!
        if (page.initializationStarted.compareAndSet(false, true)) {
            mainHandler.post { initializeOriginPage(page) }
        }
        try {
            await(page.ready, 15_000L, "System WebView XHTTP page did not initialize")
            val failure = page.error
            if (failure != null) {
                throw IOException(failure)
            }
            return page
        } catch (exception: IOException) {
            releaseOriginPage(page)
            throw exception
        }
    }

    @SuppressLint("SetJavaScriptEnabled", "AddJavascriptInterface")
    private fun newWebView(profileName: String?): WebView {
        val created = WebView(context)
        if (profileName != null) {
            WebViewCompat.setProfile(created, profileName)
        }
        created.setRendererPriorityPolicy(WebView.RENDERER_PRIORITY_IMPORTANT, false)
        val settings = created.settings
        settings.javaScriptEnabled = true
        settings.domStorageEnabled = false
        settings.allowFileAccess = false
        settings.allowContentAccess = false
        settings.cacheMode = WebSettings.LOAD_DEFAULT
        settings.mixedContentMode = WebSettings.MIXED_CONTENT_NEVER_ALLOW
        return created
    }

    @SuppressLint("AddJavascriptInterface")
    private fun initializeOriginPage(page: WebViewXhttpOriginPage) {
        if (closed.get()) {
            page.fail("System WebView is unavailable")
            return
        }
        try {
            val current = newWebView(page.binding.profileName())
            current.addJavascriptInterface(JavascriptBridge(page), "AndroidCyamlNative")
            current.webViewClient = object : WebViewClient() {
                override fun onReceivedHttpAuthRequest(
                    view: WebView,
                    handler: HttpAuthHandler,
                    host: String,
                    realm: String,
                ) {
                    if (connectProxy.isAuthenticationRealm(realm)) {
                        handler.proceed(page.binding.username(), page.binding.password())
                    } else {
                        handler.cancel()
                    }
                }

                override fun onReceivedError(
                    view: WebView,
                    request: WebResourceRequest,
                    error: WebResourceError,
                ) {
                    // Fetch failures are reported with their task id by the
                    // JavaScript bridge below. Only log a page-load failure
                    // here; canceled health checks otherwise flood warning
                    // logs with context-free net::ERR_FAILED entries.
                    if (request.isForMainFrame) {
                        Log.w(
                            TAG,
                            "Chromium page error " + error.errorCode + ": " + error.description,
                        )
                    }
                }
            }
            page.webView = current
            current.loadDataWithBaseURL(
                page.origin + "/",
                originPageSource(),
                "text/html",
                StandardCharsets.UTF_8.name(),
                null,
            )
        } catch (exception: RuntimeException) {
            page.fail(
                "Unable to load System WebView XHTTP origin: " +
                    (exception.message ?: exception.javaClass.simpleName),
            )
        }
    }

    private fun installBinaryBridge(page: WebViewXhttpOriginPage) {
        val webView = page.webView
        if (closed.get() || webView == null) {
            page.fail("System WebView is unavailable")
            return
        }
        var channel: Array<WebMessagePortCompat>? = null
        var transferred = false
        try {
            channel = WebViewCompat.createWebMessageChannel(webView)
            if (channel.size != 2) {
                throw IllegalStateException("WebView returned an invalid message channel")
            }
            val applicationPort = channel[0]
            applicationPort.setWebMessageCallback(
                messageHandler,
                object : WebMessagePortCompat.WebMessageCallbackCompat() {
                    override fun onMessage(
                        port: WebMessagePortCompat,
                        message: WebMessageCompat?,
                    ) {
                        handleBinaryBridgeMessage(page, message)
                    }
                },
            )
            page.messagePort.set(applicationPort)
            WebViewCompat.postWebMessage(
                webView,
                WebMessageCompat("androidcyaml-binary-v1", arrayOf(channel[1])),
                Uri.parse(page.origin),
            )
            transferred = true
            mainHandler.postDelayed({
                if (page.resolveBridge(false)) {
                    page.closeMessagePort()
                    disableBinaryBridgeInPage(page)
                    Log.w(TAG, "WebView binary message bridge timed out; using Base64 fallback")
                }
            }, BINARY_BRIDGE_TIMEOUT_MILLIS)
        } catch (exception: RuntimeException) {
            page.closeMessagePort()
            if (channel != null) {
                WebViewXhttpOriginPage.closeMessagePort(channel[0])
                if (!transferred) {
                    WebViewXhttpOriginPage.closeMessagePort(channel[1])
                }
            }
            if (page.resolveBridge(false)) {
                disableBinaryBridgeInPage(page)
                Log.w(
                    TAG,
                    "Unable to initialize WebView binary message bridge; using Base64 fallback",
                    exception,
                )
            }
        }
    }

    private fun handleBinaryBridgeMessage(
        page: WebViewXhttpOriginPage,
        message: WebMessageCompat?,
    ) {
        if (closed.get() ||
            message == null ||
            message.type != WebMessageCompat.TYPE_ARRAY_BUFFER
        ) {
            return
        }
        val responseFrame = WebViewBinaryBridge.decodeResponseFrame(message.arrayBuffer)
        if (responseFrame == null) {
            Log.w(TAG, "Ignoring malformed WebView binary response frame")
            return
        }
        val task = tasks[responseFrame.requestId]
        if (task == null || task.page !== page) {
            return
        }
        when (responseFrame.type) {
            WebViewBinaryBridge.TYPE_RESPONSE_CHUNK -> task.data(responseFrame.data)
            WebViewBinaryBridge.TYPE_RESPONSE_COMPLETE -> task.complete()
            WebViewBinaryBridge.TYPE_RESPONSE_ERROR -> task.fail(
                responseFrame.error.ifBlank { "System WebView fetch failed" },
            )
            WebViewBinaryBridge.TYPE_RESPONSE_HEADERS ->
                handleBinaryResponseHeaders(task, responseFrame.data)
            else -> {
                // decodeResponseFrame filters unknown message types.
            }
        }
    }

    private fun handleBinaryResponseHeaders(task: WebViewXhttpTask, payload: ByteArray) {
        try {
            val response = JSONObject(String(payload, StandardCharsets.UTF_8))
            val status = response.optInt("status", 0)
            val headers = response.optJSONObject("headers")
            if (status <= 0 || headers == null) {
                throw JSONException("Invalid response headers")
            }
            task.headers(status, response.optString("statusText", ""), headers.toString())
        } catch (exception: JSONException) {
            task.fail("Invalid response headers from System WebView")
        }
    }

    private fun releaseOriginPage(page: WebViewXhttpOriginPage) {
        page.release()
        mainHandler.post { trimIdleOriginPages() }
    }

    private fun trimIdleOriginPages() {
        var excess = pages.size - MAX_RETAINED_ORIGIN_PAGES
        if (excess <= 0) {
            return
        }
        val idle = pages.values
            .filter { it.activeRequests.get() == 0 }
            .sortedBy { it.lastUsedNanos }
        for (candidate in idle) {
            if (excess <= 0) {
                break
            }
            val removed = AtomicBoolean(false)
            pages.computeIfPresent(candidate.binding.key()) { _, current ->
                if (current === candidate && current.activeRequests.get() == 0) {
                    removed.set(true)
                    null
                } else {
                    current
                }
            }
            if (removed.get()) {
                candidate.closeMessagePort()
                destroyWebView(candidate.webView)
                candidate.webView = null
                connectProxy.unregister(candidate.binding)
                excess--
            }
        }
    }

    private fun dispatchRequestStart(
        page: WebViewXhttpOriginPage,
        task: WebViewXhttpTask,
        metadataJson: String,
    ) {
        mainHandler.post { dispatchRequestStartOnMain(page, task, metadataJson) }
    }

    private fun dispatchRequestStartOnMain(
        page: WebViewXhttpOriginPage,
        task: WebViewXhttpTask,
        metadataJson: String,
    ) {
        if (closed.get() || tasks[task.id] !== task || task.closed.get()) {
            return
        }
        val port = page.messagePort.get()
        if (page.binaryBridge.get() && port != null) {
            try {
                port.postMessage(
                    WebMessageCompat(WebViewBinaryBridge.encodeRequestStart(metadataJson)),
                )
                if (DIRECT_CONTROL_BRIDGE_LOGGED.compareAndSet(false, true)) {
                    Log.i(TAG, "Direct WebMessage XHTTP control bridge is active")
                }
                return
            } catch (exception: RuntimeException) {
                if (page.disableBinaryBridge()) {
                    disableBinaryBridgeInPage(page)
                    Log.w(
                        TAG,
                        "WebView control bridge failed; using JavaScript fallback",
                        exception,
                    )
                }
            }
        }
        val current = page.webView
        if (current == null || closed.get()) {
            task.fail("System WebView is unavailable")
            return
        }
        current.evaluateJavascript(
            "window.androidCyamlStart(" + JSONObject.quote(metadataJson) + ");",
            null,
        )
    }

    private fun stopMessageHandlerThread() {
        messageHandlerThread?.quitSafely()
    }

    private fun disableBinaryBridgeInPage(page: WebViewXhttpOriginPage) {
        mainHandler.post {
            val current = page.webView
            if (current != null && !closed.get()) {
                current.evaluateJavascript("window.androidCyamlDisableBinaryBridge();", null)
            }
        }
    }

    private fun installProxyOverride() {
        if (!WebViewFeature.isFeatureSupported(WebViewFeature.PROXY_OVERRIDE)) {
            throw IOException("当前 Android System WebView 不支持进程级代理覆写")
        }
        val proxyConfig = ProxyConfig.Builder()
            .addProxyRule(connectProxy.authority())
            .build()
        val applied = CountDownLatch(1)
        try {
            ProxyController.getInstance().setProxyOverride(
                proxyConfig,
                { runnable -> runnable.run() },
                { applied.countDown() },
            )
        } catch (exception: IllegalArgumentException) {
            throw IOException("无法配置 System WebView CONNECT 代理", exception)
        } catch (exception: UnsupportedOperationException) {
            throw IOException("无法配置 System WebView CONNECT 代理", exception)
        }
        await(applied, 10_000L, "System WebView CONNECT 代理应用超时")
        proxyOverrideInstalled.set(true)
    }

    private fun clearProxyOverride() {
        if (!proxyOverrideInstalled.compareAndSet(true, false)) {
            return
        }
        try {
            ProxyController.getInstance().clearProxyOverride({ runnable -> runnable.run() }) {}
        } catch (exception: RuntimeException) {
            Log.w(TAG, "Unable to clear System WebView proxy override", exception)
        }
    }

    private fun dispatchRequestBodyChunk(
        page: WebViewXhttpOriginPage?,
        task: WebViewXhttpTask?,
        bodyId: Long,
        readId: Long,
        status: Int,
        chunk: ByteArray?,
        count: Int,
    ) {
        mainHandler.post {
            dispatchRequestBodyChunkOnMain(page, task, bodyId, readId, status, chunk, count)
        }
    }

    private fun dispatchRequestBodyChunkOnMain(
        page: WebViewXhttpOriginPage?,
        task: WebViewXhttpTask?,
        bodyId: Long,
        readId: Long,
        status: Int,
        chunk: ByteArray?,
        count: Int,
    ) {
        val webView = page?.webView
        if (closed.get() || webView == null) {
            return
        }
        if (task != null &&
            (tasksByRequestBody[bodyId] !== task || task.requestBodyClosed.get())
        ) {
            return
        }
        val port = page.messagePort.get()
        if (page.binaryBridge.get() && port != null) {
            try {
                port.postMessage(
                    WebMessageCompat(
                        WebViewBinaryBridge.encodeRequestBodyChunk(
                            bodyId,
                            readId,
                            status,
                            chunk,
                            count,
                        ),
                    ),
                )
                return
            } catch (exception: RuntimeException) {
                if (page.disableBinaryBridge()) {
                    disableBinaryBridgeInPage(page)
                    Log.w(
                        TAG,
                        "WebView binary message bridge failed; using Base64 fallback",
                        exception,
                    )
                }
            }
        }
        val encoded = if (status > 0 && chunk != null && count > 0) {
            Base64.encodeToString(chunk, 0, count, Base64.NO_WRAP)
        } else {
            ""
        }
        webView.evaluateJavascript(
            "window.androidCyamlBodyChunk(" +
                bodyId + "," +
                readId + "," +
                status + "," +
                JSONObject.quote(encoded ?: "") +
                ");",
            null,
        )
    }

    private inner class JavascriptBridge(private val page: WebViewXhttpOriginPage?) {
        @JavascriptInterface
        fun onReady(supportsRequestStreaming: Boolean) {
            val current = page
            if (current == null) {
                requestStreamingSupported = supportsRequestStreaming
                webViewReady.countDown()
                return
            }
            if (supportsRequestStreaming != requestStreamingSupported) {
                current.fail("System WebView request-stream capability changed during startup")
                return
            }
            if (!binaryBridgeSupported) {
                current.resolveBridge(false)
                return
            }
            if (current.bridgeInstallationStarted.compareAndSet(false, true)) {
                mainHandler.post { installBinaryBridge(current) }
            }
        }

        @JavascriptInterface
        fun onMessagePortReady() {
            val current = page ?: return
            if (current.resolveBridge(true)) {
                Log.i(TAG, "WebView binary message bridge is active for " + current.origin)
            } else if (!current.binaryBridge.get()) {
                current.closeMessagePort()
                disableBinaryBridgeInPage(current)
            }
        }

        @JavascriptInterface
        fun requestBodyLength(id: Long): Int = tasks[id]?.requestBody?.size ?: 0

        @JavascriptInterface
        fun requestBodyChunk(id: Long, offset: Int, maximum: Int): String {
            val task = tasks[id]
            if (task == null || offset < 0 || offset >= task.requestBody.size) {
                return ""
            }
            val length = minOf(
                maxOf(maximum, 1),
                BODY_CHUNK_BYTES,
                task.requestBody.size - offset,
            )
            return Base64.encodeToString(
                task.requestBody.copyOfRange(offset, offset + length),
                Base64.NO_WRAP,
            )
        }

        @JavascriptInterface
        fun readRequestBodyChunk(bodyId: Long, readId: Long, maximum: Int) {
            val task = tasksByRequestBody[bodyId]
            if (page == null ||
                bodyId <= 0L ||
                readId <= 0L ||
                closed.get() ||
                task == null ||
                task.page !== page ||
                task.requestBodyClosed.get()
            ) {
                dispatchRequestBodyChunk(page, null, bodyId, readId, -1, null, 0)
                return
            }
            val capacity = minOf(maxOf(maximum, 1), BODY_CHUNK_BYTES)
            try {
                requestBodyExecutor.execute {
                    try {
                        val chunk = ByteArray(capacity)
                        val count = MihomoNative.readBrowserRequestBody(bodyId, chunk)
                        if (tasksByRequestBody[bodyId] !== task ||
                            task.requestBodyClosed.get() ||
                            closed.get()
                        ) {
                            return@execute
                        }
                        when {
                            count < 0 || count > capacity ->
                                dispatchRequestBodyChunk(page, task, bodyId, readId, -1, null, 0)
                            count == 0 ->
                                dispatchRequestBodyChunk(page, task, bodyId, readId, 0, null, 0)
                            else ->
                                dispatchRequestBodyChunk(
                                    page,
                                    task,
                                    bodyId,
                                    readId,
                                    1,
                                    chunk,
                                    count,
                                )
                        }
                    } catch (exception: RuntimeException) {
                        Log.w(TAG, "Unable to read WebView request body", exception)
                        dispatchRequestBodyChunk(page, task, bodyId, readId, -1, null, 0)
                    }
                }
            } catch (exception: RejectedExecutionException) {
                dispatchRequestBodyChunk(page, task, bodyId, readId, -1, null, 0)
            }
        }

        @JavascriptInterface
        fun closeRequestBody(bodyId: Long) {
            MihomoNative.closeBrowserRequestBody(bodyId)
        }

        @JavascriptInterface
        fun onHeaders(id: Long, status: Int, statusText: String?, headersJson: String?) {
            tasks[id]?.headers(status, statusText, headersJson)
        }

        @JavascriptInterface
        fun onChunk(id: Long, encoded: String?) {
            val task = tasks[id]
            if (task == null || encoded.isNullOrEmpty()) {
                return
            }
            try {
                task.data(Base64.decode(encoded, Base64.DEFAULT))
            } catch (exception: IllegalArgumentException) {
                task.fail("Invalid response chunk from System WebView")
            }
        }

        @JavascriptInterface
        fun onComplete(id: Long) {
            tasks[id]?.complete()
        }

        @JavascriptInterface
        fun onError(id: Long, message: String?) {
            val task = tasks[id] ?: return
            Log.w(TAG, "Chromium fetch failed: $message")
            task.fail(
                if (message.isNullOrBlank()) "System WebView fetch failed" else message,
            )
        }
    }

    companion object {
        const val TAG = "AndroidCyaml/WebViewXHTTP"
        private const val START_TIMEOUT_MILLIS = 45_000L
        private const val BINARY_BRIDGE_TIMEOUT_MILLIS = 3_000L
        private const val BODY_CHUNK_BYTES = 48 * 1024
        private const val MAX_RETAINED_ORIGIN_PAGES = 4

        val DIRECT_RESPONSE_BRIDGE_LOGGED = AtomicBoolean(false)

        private val DIRECT_CONTROL_BRIDGE_LOGGED = AtomicBoolean(false)

        fun originOf(urlValue: String?): String {
            val uri = try {
                URI.create(urlValue ?: "")
            } catch (exception: IllegalArgumentException) {
                throw IOException("Invalid System WebView XHTTP URL", exception)
            }
            if (!"https".equals(uri.scheme, ignoreCase = true) ||
                uri.host.isNullOrBlank() ||
                uri.userInfo != null
            ) {
                throw IOException("System WebView XHTTP only accepts HTTPS origin URLs")
            }
            var host = uri.host.lowercase(Locale.ROOT)
            if (host.indexOf(':') >= 0 && !(host.startsWith("[") && host.endsWith("]"))) {
                host = "[$host]"
            }
            val port = uri.port
            return "https://" + host + (if (port > 0 && port != 443) ":$port" else "")
        }

        private fun originPageSource(): String = WebViewXhttpBridgeScript.SOURCE.replace(
            "<meta charset=\"utf-8\">",
            "<meta charset=\"utf-8\">\n<link rel=\"preconnect\" href=\"/\">",
        )

        private fun supportsBinaryWebMessages(): Boolean =
            WebViewFeature.isFeatureSupported(WebViewFeature.CREATE_WEB_MESSAGE_CHANNEL) &&
                WebViewFeature.isFeatureSupported(WebViewFeature.POST_WEB_MESSAGE) &&
                WebViewFeature.isFeatureSupported(
                    WebViewFeature.WEB_MESSAGE_PORT_POST_MESSAGE,
                ) &&
                WebViewFeature.isFeatureSupported(
                    WebViewFeature.WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK,
                ) &&
                WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_ARRAY_BUFFER)

        private fun destroyWebView(current: WebView?) {
            if (current == null) {
                return
            }
            current.stopLoading()
            current.removeJavascriptInterface("AndroidCyamlNative")
            current.webViewClient = WebViewClient()
            current.destroy()
        }

        private fun await(latch: CountDownLatch, timeout: Long, message: String) {
            try {
                if (!latch.await(timeout, TimeUnit.MILLISECONDS)) {
                    throw IOException(message)
                }
            } catch (exception: InterruptedException) {
                Thread.currentThread().interrupt()
                throw IOException(message, exception)
            }
        }

        private fun errorResult(message: String?): String = try {
            JSONObject()
                .put("error", message ?: "System WebView XHTTP failed")
                .toString()
        } catch (impossible: JSONException) {
            "{\"error\":\"System WebView XHTTP failed\"}"
        }
    }
}
