package io.github.qwqgong.androidcyaml;

import android.annotation.SuppressLint;
import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.Base64;
import android.util.Log;
import android.webkit.JavascriptInterface;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Executes XHTTP HTTP requests through Android System WebView.
 *
 * <p>The mihomo core keeps XHTTP framing, session identifiers and packet-up
 * batching. Only the final HTTP request/response is bridged through JNI so TLS,
 * HTTP/2 headers, connection reuse and browser side traffic are generated by
 * the installed WebView Chromium provider.</p>
 */
final class WebViewXhttpDialer implements AutoCloseable {
    private static final String TAG = "AndroidCyaml/WebViewXHTTP";
    private static final long START_TIMEOUT_MILLIS = 45_000L;
    private static final int BODY_CHUNK_BYTES = 48 * 1024;
    private static final String BASE_URL = "https://androidcyaml.invalid/";

    private static final String PAGE = """
            <!doctype html>
            <meta charset="utf-8">
            <script>
            "use strict";
            (() => {
              const controllers = new Map();
              const forbidden = new Set([
                "host", "content-length", "transfer-encoding", "connection",
                "upgrade", "proxy-connection", "proxy-authorization",
                "user-agent", "accept-encoding", "origin", "cookie"
              ]);

              function decodeBase64(value) {
                const binary = atob(value);
                const output = new Uint8Array(binary.length);
                for (let i = 0; i < binary.length; i++) output[i] = binary.charCodeAt(i);
                return output;
              }

              function encodeBase64(value) {
                let binary = "";
                const step = 0x8000;
                for (let offset = 0; offset < value.length; offset += step) {
                  const part = value.subarray(offset, Math.min(value.length, offset + step));
                  binary += String.fromCharCode.apply(null, part);
                }
                return btoa(binary);
              }

              function requestBody(id) {
                const length = AndroidCyamlNative.requestBodyLength(id);
                if (length <= 0) return null;
                const output = new Uint8Array(length);
                let offset = 0;
                while (offset < length) {
                  const encoded = AndroidCyamlNative.requestBodyChunk(id, offset, 49152);
                  if (!encoded) throw new Error("request body bridge ended early");
                  const part = decodeBase64(encoded);
                  output.set(part, offset);
                  offset += part.length;
                }
                return output;
              }

              function prepare(meta) {
                const init = {
                  method: meta.method,
                  cache: "no-store",
                  credentials: "include",
                  redirect: "follow"
                };
                const headers = new Headers();
                let referrer = "";
                for (const [name, values] of Object.entries(meta.headers || {})) {
                  const lower = name.toLowerCase();
                  if (lower === "referer") {
                    if (values && values.length) referrer = values[0];
                    continue;
                  }
                  if (forbidden.has(lower) || lower.startsWith("sec-") || lower.startsWith("proxy-")) {
                    continue;
                  }
                  for (const value of values || []) {
                    try { headers.append(name, value); } catch (_) {}
                  }
                }
                init.headers = headers;
                if (referrer) {
                  try {
                    const parsed = new URL(referrer);
                    init.referrer = new URL(parsed.pathname + parsed.search + parsed.hash, document.baseURI).href;
                    init.referrerPolicy = "unsafe-url";
                  } catch (_) {}
                }
                if (meta.method !== "GET" && meta.method !== "HEAD") {
                  const body = requestBody(meta.id);
                  if (body && body.length) init.body = body;
                }
                return init;
              }

              window.androidCyamlStart = async encoded => {
                const meta = JSON.parse(encoded);
                const controller = new AbortController();
                controllers.set(meta.id, controller);
                try {
                  const init = prepare(meta);
                  init.signal = controller.signal;
                  const response = await fetch(meta.url, init);
                  const headers = {};
                  response.headers.forEach((value, name) => { headers[name] = [value]; });
                  AndroidCyamlNative.onHeaders(
                    meta.id,
                    response.status,
                    response.statusText || "",
                    JSON.stringify(headers)
                  );
                  if (!response.body) {
                    AndroidCyamlNative.onComplete(meta.id);
                    return;
                  }
                  const reader = response.body.getReader();
                  while (true) {
                    const result = await reader.read();
                    if (result.value && result.value.byteLength) {
                      AndroidCyamlNative.onChunk(meta.id, encodeBase64(result.value));
                    }
                    if (result.done) break;
                  }
                  AndroidCyamlNative.onComplete(meta.id);
                } catch (error) {
                  AndroidCyamlNative.onError(meta.id, String(error && error.message ? error.message : error));
                } finally {
                  controllers.delete(meta.id);
                }
              };

              window.androidCyamlCancel = id => {
                const controller = controllers.get(id);
                if (controller) controller.abort();
                controllers.delete(id);
              };

              AndroidCyamlNative.onReady();
            })();
            </script>
            """;

    private final Handler mainHandler = new Handler(Looper.getMainLooper());
    private final ConcurrentHashMap<Long, Task> tasks = new ConcurrentHashMap<>();
    private final AtomicLong nextId = new AtomicLong(1L);
    private final CountDownLatch ready = new CountDownLatch(1);
    private final AtomicBoolean closed = new AtomicBoolean(false);
    private volatile WebView webView;

    WebViewXhttpDialer(Context context) throws IOException {
        Objects.requireNonNull(context);
        Runnable create = () -> createWebView(context.getApplicationContext());
        if (Looper.myLooper() == Looper.getMainLooper()) {
            create.run();
        } else {
            mainHandler.post(create);
        }
        await(ready, 15_000L, "System WebView did not initialize");
    }

    String startRequest(String requestJson, byte[] body) {
        if (closed.get()) {
            return errorResult("System WebView XHTTP dialer is closed");
        }
        final JSONObject metadata;
        try {
            metadata = new JSONObject(requestJson == null ? "{}" : requestJson);
            String url = metadata.optString("url", "");
            if (!url.startsWith("https://")) {
                return errorResult("System WebView XHTTP only accepts https URLs");
            }
        } catch (JSONException exception) {
            return errorResult("Invalid WebView XHTTP request metadata");
        }

        long id = nextId.getAndIncrement();
        Task task = new Task(id, body == null ? new byte[0] : body.clone());
        tasks.put(id, task);
        try {
            metadata.put("id", id);
        } catch (JSONException exception) {
            tasks.remove(id);
            return errorResult("Unable to assign WebView XHTTP request id");
        }

        mainHandler.post(() -> {
            WebView current = webView;
            if (current == null || closed.get()) {
                task.fail("System WebView is unavailable");
                return;
            }
            String argument = JSONObject.quote(metadata.toString());
            current.evaluateJavascript("window.androidCyamlStart(" + argument + ");", null);
        });

        try {
            if (!task.headersReady.await(START_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)) {
                closeRequest(id);
                return errorResult("System WebView XHTTP response header timeout");
            }
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            closeRequest(id);
            return errorResult("System WebView XHTTP request interrupted");
        }

        if (task.error != null) {
            tasks.remove(id);
            return errorResult(task.error);
        }
        try {
            JSONObject result = new JSONObject();
            result.put("id", id);
            result.put("status", task.statusCode);
            result.put("statusText", task.statusText == null ? "" : task.statusText);
            result.put("headers", new JSONObject(task.headersJson == null ? "{}" : task.headersJson));
            return result.toString();
        } catch (JSONException exception) {
            closeRequest(id);
            return errorResult("Unable to encode System WebView response headers");
        }
    }

    int readResponse(long id, byte[] destination) {
        Task task = tasks.get(id);
        if (task == null || destination == null || destination.length == 0) {
            return task == null ? -1 : 0;
        }
        try {
            return task.read(destination);
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            return -1;
        }
    }

    void closeRequest(long id) {
        Task task = tasks.remove(id);
        if (task != null) {
            task.close();
        }
        mainHandler.post(() -> {
            WebView current = webView;
            if (current != null) {
                current.evaluateJavascript("window.androidCyamlCancel(" + id + ");", null);
            }
        });
    }

    @Override
    public void close() {
        if (!closed.compareAndSet(false, true)) {
            return;
        }
        tasks.forEach((id, task) -> task.close());
        tasks.clear();
        mainHandler.post(() -> {
            WebView current = webView;
            webView = null;
            if (current != null) {
                current.stopLoading();
                current.removeJavascriptInterface("AndroidCyamlNative");
                current.destroy();
            }
        });
    }

    @SuppressLint({"SetJavaScriptEnabled", "AddJavascriptInterface"})
    private void createWebView(Context context) {
        if (closed.get()) {
            ready.countDown();
            return;
        }
        try {
            WebView created = new WebView(context);
            WebSettings settings = created.getSettings();
            settings.setJavaScriptEnabled(true);
            settings.setDomStorageEnabled(false);
            settings.setAllowFileAccess(false);
            settings.setAllowContentAccess(false);
            settings.setCacheMode(WebSettings.LOAD_DEFAULT);
            settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);
            created.addJavascriptInterface(new JavascriptBridge(), "AndroidCyamlNative");
            created.setWebViewClient(new WebViewClient());
            webView = created;
            created.loadDataWithBaseURL(BASE_URL, PAGE, "text/html", StandardCharsets.UTF_8.name(), null);
        } catch (RuntimeException exception) {
            Log.e(TAG, "Unable to create System WebView XHTTP dialer", exception);
            ready.countDown();
        }
    }

    private static void await(CountDownLatch latch, long timeout, String message) throws IOException {
        try {
            if (!latch.await(timeout, TimeUnit.MILLISECONDS)) {
                throw new IOException(message);
            }
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new IOException(message, exception);
        }
    }

    private static String errorResult(String message) {
        try {
            return new JSONObject().put("error", message == null ? "System WebView XHTTP failed" : message).toString();
        } catch (JSONException impossible) {
            return "{\"error\":\"System WebView XHTTP failed\"}";
        }
    }

    private final class JavascriptBridge {
        @JavascriptInterface
        public void onReady() {
            ready.countDown();
        }

        @JavascriptInterface
        public int requestBodyLength(long id) {
            Task task = tasks.get(id);
            return task == null ? 0 : task.requestBody.length;
        }

        @JavascriptInterface
        public String requestBodyChunk(long id, int offset, int maximum) {
            Task task = tasks.get(id);
            if (task == null || offset < 0 || offset >= task.requestBody.length) {
                return "";
            }
            int length = Math.min(Math.min(Math.max(maximum, 1), BODY_CHUNK_BYTES), task.requestBody.length - offset);
            return Base64.encodeToString(
                    Arrays.copyOfRange(task.requestBody, offset, offset + length),
                    Base64.NO_WRAP
            );
        }

        @JavascriptInterface
        public void onHeaders(long id, int status, String statusText, String headersJson) {
            Task task = tasks.get(id);
            if (task != null) {
                task.headers(status, statusText, headersJson);
            }
        }

        @JavascriptInterface
        public void onChunk(long id, String encoded) {
            Task task = tasks.get(id);
            if (task == null || encoded == null || encoded.isEmpty()) {
                return;
            }
            try {
                task.data(Base64.decode(encoded, Base64.DEFAULT));
            } catch (IllegalArgumentException exception) {
                task.fail("Invalid response chunk from System WebView");
            }
        }

        @JavascriptInterface
        public void onComplete(long id) {
            Task task = tasks.get(id);
            if (task != null) {
                task.complete();
            }
        }

        @JavascriptInterface
        public void onError(long id, String message) {
            Task task = tasks.get(id);
            if (task != null) {
                task.fail(message == null || message.isBlank()
                        ? "System WebView fetch failed"
                        : message);
            }
        }
    }

    private static final class Task {
        private static final Chunk EOF = new Chunk(new byte[0], true, null);

        final long id;
        final byte[] requestBody;
        final CountDownLatch headersReady = new CountDownLatch(1);
        final LinkedBlockingQueue<Chunk> response = new LinkedBlockingQueue<>();
        final AtomicBoolean closed = new AtomicBoolean(false);
        volatile int statusCode;
        volatile String statusText;
        volatile String headersJson;
        volatile String error;
        private Chunk current;
        private int currentOffset;

        Task(long id, byte[] requestBody) {
            this.id = id;
            this.requestBody = requestBody;
        }

        void headers(int status, String text, String encodedHeaders) {
            if (headersReady.getCount() == 0) {
                return;
            }
            statusCode = status;
            statusText = text;
            headersJson = encodedHeaders;
            headersReady.countDown();
        }

        void data(byte[] bytes) {
            if (!closed.get() && bytes != null && bytes.length != 0) {
                response.offer(new Chunk(bytes, false, null));
            }
        }

        void complete() {
            headersReady.countDown();
            response.offer(EOF);
        }

        void fail(String message) {
            error = message == null ? "System WebView XHTTP failed" : message;
            headersReady.countDown();
            response.offer(new Chunk(new byte[0], false, error));
        }

        synchronized int read(byte[] destination) throws InterruptedException {
            while (true) {
                if (current != null && currentOffset < current.data.length) {
                    int count = Math.min(destination.length, current.data.length - currentOffset);
                    System.arraycopy(current.data, currentOffset, destination, 0, count);
                    currentOffset += count;
                    if (currentOffset >= current.data.length) {
                        current = null;
                        currentOffset = 0;
                    }
                    return count;
                }
                Chunk next = response.take();
                if (next.error != null) {
                    return -1;
                }
                if (next.eof) {
                    return 0;
                }
                current = next;
                currentOffset = 0;
            }
        }

        void close() {
            if (closed.compareAndSet(false, true)) {
                response.clear();
                response.offer(EOF);
                headersReady.countDown();
            }
        }
    }

    private record Chunk(byte[] data, boolean eof, String error) {}
}
